/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "eufy-security adapter settings": {
        "en": "Adapter settings for eufy-security",
        "de": "Adaptereinstellungen für eufy-security",
        "ru": "Настройки адаптера для eufy-security",
        "pt": "Configurações do adaptador para eufy-security",
        "nl": "Adapterinstellingen voor eufy-security",
        "fr": "Paramètres d'adaptateur pour eufy-security",
        "it": "Impostazioni dell'adattatore per eufy-security",
        "es": "Ajustes del adaptador para eufy-security",
        "pl": "Ustawienia adaptera dla eufy-security",
        "zh-cn": "eufy-security的适配器设置"
    },
    "Username": {
        "en": "Username",
        "de": "Benutzername",
        "ru": "Имя пользователя",
        "pt": "Nome de usuário",
        "nl": "Gebruikersnaam",
        "fr": "Nom d'utilisateur",
        "it": "Nome utente",
        "es": "Nombre de usuario",
        "pl": "Nazwa użytkownika",
        "zh-cn": "帳號"
    },
    "Password": {
        "en": "Password",
        "de": "Passwort",
        "ru": "Пароль",
        "pt": "Senha",
        "nl": "Wachtwoord",
        "fr": "Mot de passe",
        "it": "Password",
        "es": "Contraseña",
        "pl": "Hasło",
        "zh-cn": "密码"
    },
    "Polling interval (min)": {
        "en": "Polling interval (min)",
        "de": "Abfrageintervall (min)",
        "ru": "Интервал опроса (мин)",
        "pt": "Intervalo de sondagem (min)",
        "nl": "Polling-interval (min)",
        "fr": "Intervalle d'interrogation (min)",
        "it": "Intervallo di polling (min)",
        "es": "Intervalo de sondeo (min)",
        "pl": "Okres odpytywania (min)",
        "zh-cn": "轮询间隔（分钟）"
    },
    "Max camera livestream duration (sec)": {
        "en": "Max camera livestream duration (sec; 0 = unlimited)",
        "de": "Maximale Livestream-Dauer der Kamera (Sek.; 0 = unbegrenzt)",
        "ru": "Максимальная продолжительность прямой трансляции с камеры (сек; 0 = неограниченно)",
        "pt": "Duração máxima da transmissão ao vivo da câmera (segundos; 0 = ilimitado)",
        "nl": "Max. Duur livestream camera (sec; 0 = onbeperkt)",
        "fr": "Durée maximale de la diffusion en direct de la caméra (s; 0 = illimité)",
        "it": "Durata massima del live streaming della videocamera (sec 0 = illimitata)",
        "es": "Duración máxima de la transmisión en vivo de la cámara (segundos; 0 = ilimitado)",
        "pl": "Maksymalny czas trwania transmisji na żywo z kamery (s; 0 = bez ograniczeń)",
        "zh-cn": "相机直播的最大持续时间（秒；0 = 无限）"
    },
    "Time in seconds before event reset": {
        "en": "Time in seconds before event reset",
        "de": "Zeit in Sekunden vor dem Zurücksetzen des Ereignisses",
        "ru": "Время в секундах до сброса события",
        "pt": "Tempo em segundos antes da redefinição do evento",
        "nl": "Tijd in seconden voordat de gebeurtenis wordt gereset",
        "fr": "Temps en secondes avant la réinitialisation de l'événement",
        "it": "Tempo in secondi prima del ripristino dell'evento",
        "es": "Tiempo en segundos antes del reinicio del evento",
        "pl": "Czas w sekundach do zresetowania zdarzenia",
        "zh-cn": "事件重置之前的时间（以秒为单位）"
    },
    "Authentication settings": {
        "en": "Authentication settings",
        "de": "Authentifizierungseinstellungen",
        "ru": "Настройки аутентификации",
        "pt": "Configurações de autenticação",
        "nl": "Authenticatie-instellingen",
        "fr": "Paramètres d'authentification",
        "it": "Impostazioni di autenticazione",
        "es": "Configuración de autenticación",
        "pl": "Ustawienia uwierzytelniania",
        "zh-cn": "验证设定"
    },
    "Other settings": {
        "en": "Other settings",
        "de": "Andere Einstellungen",
        "ru": "Другие настройки",
        "pt": "Outros ajustes",
        "nl": "Andere instellingen",
        "fr": "Autres réglages",
        "it": "Altre impostazioni",
        "es": "Otros ajustes",
        "pl": "Inne ustawienia",
        "zh-cn": "其他设定"
    },
    "Settings": {
        "en": "Settings",
        "de": "Einstellungen",
        "ru": "Настройки",
        "pt": "Configurações",
        "nl": "Instellingen",
        "fr": "Réglages",
        "it": "Impostazioni",
        "es": "Ajustes",
        "pl": "Ustawienia",
        "zh-cn": "设定值"
    },
    "Main settings": {
        "en": "Main settings",
        "de": "Haupteinstellungen",
        "ru": "Основные параметры",
        "pt": "Configurações principais",
        "nl": "Belangrijkste instellingen",
        "fr": "Réglages principaux",
        "it": "Impostazioni principali",
        "es": "Ajustes principales",
        "pl": "Ustawienia główne",
        "zh-cn": "主要设定"
    },
    "Livestream settings": {
        "en": "Livestream settings",
        "de": "Livestream-Einstellungen",
        "ru": "Настройки прямой трансляции",
        "pt": "Configurações de transmissão ao vivo",
        "nl": "Livestream-instellingen",
        "fr": "Paramètres de diffusion en direct",
        "it": "Impostazioni live streaming",
        "es": "Configuración de transmisión en vivo",
        "pl": "Ustawienia transmisji na żywo",
        "zh-cn": "直播设置"
    },
    "Only local connection": {
        "en": "Only local connection",
        "de": "Nur lokale Verbindung",
        "ru": "Только локальное подключение",
        "pt": "Apenas conexão local",
        "nl": "Alleen lokale verbinding",
        "fr": "Uniquement connexion locale",
        "it": "Solo connessione locale",
        "es": "Solo conexión local",
        "pl": "Tylko połączenie lokalne",
        "zh-cn": "仅本地连接"
    },
    "Quickest connection": {
        "en": "Quickest connection",
        "de": "Schnellste Verbindung",
        "ru": "Самое быстрое соединение",
        "pt": "Conexão mais rápida",
        "nl": "Snelste verbinding",
        "fr": "Connexion la plus rapide",
        "it": "Connessione più veloce",
        "es": "Conexión más rápida",
        "pl": "Najszybsze połączenie",
        "zh-cn": "最快的连接"
    },
    "P2P connection type": {
        "en": "P2P connection type",
        "de": "P2P-Verbindungstyp",
        "ru": "Тип подключения P2P",
        "pt": "Tipo de conexão P2P",
        "nl": "P2P-verbindingstype",
        "fr": "Type de connexion P2P",
        "it": "Tipo di connessione P2P",
        "es": "Tipo de conexión P2P",
        "pl": "Typ połączenia P2P",
        "zh-cn": "P2P连接类型"
    },
    "Accept incoming invitations": {
        "en": "Accept incoming invitations",
        "de": "Eingehende Einladungen annehmen",
        "ru": "Принимать входящие приглашения",
        "pt": "Aceitar os convites recebidos",
        "nl": "Accepteer inkomende uitnodigingen",
        "fr": "Accepter les invitations entrantes",
        "it": "Accetta inviti in arrivo",
        "es": "Aceptar invitaciones entrantes",
        "pl": "Przyjmowanie zaproszeń przychodzących",
        "zh-cn": "接受收到的邀请"
    },
    "Alarm sound duration (sec)": {
        "en": "Alarm sound duration (sec)",
        "de": "Dauer des Alarmtons (Sek.)",
        "ru": "Длительность звукового сигнала тревоги (сек)",
        "pt": "Duração do som do alarme (seg)",
        "nl": "Duur alarmgeluid (sec)",
        "fr": "Durée du son de l'alarme (sec)",
        "it": "Durata del suono dell'allarme (sec)",
        "es": "Duración del sonido de la alarma (s)",
        "pl": "Czas trwania dźwięku alarmu (sek.)",
        "zh-cn": "警报声持续时间（秒"
    },
    "inherited from ioBroker": {
        "en": "inherited from ioBroker",
        "de": "von ioBroker geerbt",
        "ru": "наследуется от ioBroker",
        "pt": "herdado de ioBroker",
        "nl": "geërfd van ioBroker",
        "fr": "hérité de ioBroker",
        "it": "ereditato da ioBroker",
        "es": "heredado de ioBroker",
        "pl": "odziedziczone po ioBroker",
        "zh-cn": "继承于 ioBroker"
    },
    "Afghanistan":{
        "en":"Afghanistan",
        "de":"Afghanistan",
        "ru":"Афганистан",
        "pt":"Afeganistão",
        "nl":"Afghanistan",
        "fr":"Afghanistan",
        "it":"Afghanistan",
        "es":"Afganistán",
        "pl":"Afganistan",
        "zh-cn":"阿富汗"
    },
    "Albania":{
        "en":"Albania",
        "de":"Albanien",
        "ru":"Албания",
        "pt":"Albânia",
        "nl":"Albanië",
        "fr":"Albanie",
        "it":"Albania",
        "es":"Albania",
        "pl":"Albania",
        "zh-cn":"阿尔巴尼亚"
    },
    "Algeria":{
        "en":"Algeria",
        "de":"Algerien",
        "ru":"Алжир",
        "pt":"Argélia",
        "nl":"Algerije",
        "fr":"Algérie",
        "it":"Algeria",
        "es":"Argelia",
        "pl":"Algieria",
        "zh-cn":"阿尔及利亚"
    },
    "American Samoa":{
        "en":"American Samoa",
        "de":"Amerikanisch-Samoa",
        "ru":"Американское Самоа",
        "pt":"Samoa Americana",
        "nl":"Amerikaans-Samoa",
        "fr":"Samoa américaines",
        "it":"Samoa Americane",
        "es":"Samoa Americana",
        "pl":"Samoa Amerykańskie",
        "zh-cn":"美属萨摩亚"
    },
    "Andorra":{
        "en":"Andorra",
        "de":"Andorra",
        "ru":"Андорра",
        "pt":"Andorra",
        "nl":"Andorra",
        "fr":"Andorre",
        "it":"Andorra",
        "es":"Andorra",
        "pl":"Andora",
        "zh-cn":"安道尔"
    },
    "Angola":{
        "en":"Angola",
        "de":"Angola",
        "ru":"Ангола",
        "pt":"Angola",
        "nl":"Angola",
        "fr":"Angola",
        "it":"Angola",
        "es":"Angola",
        "pl":"Angola",
        "zh-cn":"安哥拉"
    },
    "Anguilla":{
        "en":"Anguilla",
        "de":"Anguilla",
        "ru":"Ангилья",
        "pt":"Anguila",
        "nl":"Anguilla",
        "fr":"Anguilla",
        "it":"Anguilla",
        "es":"Anguila",
        "pl":"Anguilla",
        "zh-cn":"安圭拉"
    },
    "Antarctica":{
        "en":"Antarctica",
        "de":"Antarktis",
        "ru":"Антарктида",
        "pt":"Antártida",
        "nl":"Antarctica",
        "fr":"Antarctique",
        "it":"Antartide",
        "es":"Antártida",
        "pl":"Antarktyka",
        "zh-cn":"南极洲"
    },
    "Antigua and Barbuda":{
        "en":"Antigua and Barbuda",
        "de":"Antigua und Barbuda",
        "ru":"Антигуа и Барбуда",
        "pt":"Antígua e Barbuda",
        "nl":"Antigua en Barbuda",
        "fr":"Antigua-et-Barbuda",
        "it":"Antigua e Barbuda",
        "es":"Antigua y Barbuda",
        "pl":"Antigua i Barbuda",
        "zh-cn":"安提瓜和巴布达"
    },
    "Argentina":{
        "en":"Argentina",
        "de":"Argentinien",
        "ru":"Аргентина",
        "pt":"Argentina",
        "nl":"Argentinië",
        "fr":"Argentine",
        "it":"Argentina",
        "es":"Argentina",
        "pl":"Argentyna",
        "zh-cn":"阿根廷"
    },
    "Armenia":{
        "en":"Armenia",
        "de":"Armenien",
        "ru":"Армения",
        "pt":"Arménia",
        "nl":"Armenië",
        "fr":"Arménie",
        "it":"Armenia",
        "es":"Armenia",
        "pl":"Armenia",
        "zh-cn":"亚美尼亚"
    },
    "Aruba":{
        "en":"Aruba",
        "de":"Aruba",
        "ru":"Аруба",
        "pt":"Aruba",
        "nl":"Aruba",
        "fr":"Aruba",
        "it":"Aruba",
        "es":"Aruba",
        "pl":"Aruba",
        "zh-cn":"阿鲁巴"
    },
    "Australia":{
        "en":"Australia",
        "de":"Australien",
        "ru":"Австралия",
        "pt":"Austrália",
        "nl":"Australië",
        "fr":"Australie",
        "it":"Australia",
        "es":"Australia",
        "pl":"Australia",
        "zh-cn":"澳大利亚"
    },
    "Austria":{
        "en":"Austria",
        "de":"Österreich",
        "ru":"Австрия",
        "pt":"Áustria",
        "nl":"Oostenrijk",
        "fr":"Autriche",
        "it":"Austria",
        "es":"Austria",
        "pl":"Austria",
        "zh-cn":"奥地利"
    },
    "Azerbaijan":{
        "en":"Azerbaijan",
        "de":"Aserbaidschan",
        "ru":"Азербайджан",
        "pt":"Azerbaijão",
        "nl":"Azerbeidzjan",
        "fr":"Azerbaïdjan",
        "it":"Azerbaigian",
        "es":"Azerbaiyán",
        "pl":"Azerbejdżan",
        "zh-cn":"阿塞拜疆"
    },
    "Bahamas":{
        "en":"Bahamas",
        "de":"Bahamas",
        "ru":"Багамы",
        "pt":"Bahamas",
        "nl":"Bahama's",
        "fr":"Bahamas",
        "it":"Bahamas",
        "es":"Bahamas",
        "pl":"Bahamy",
        "zh-cn":"巴哈马"
    },
    "Bahrain":{
        "en":"Bahrain",
        "de":"Bahrain",
        "ru":"Бахрейн",
        "pt":"Bahrein",
        "nl":"Bahrein",
        "fr":"Bahreïn",
        "it":"Bahrain",
        "es":"Bahrein",
        "pl":"Bahrajn",
        "zh-cn":"巴林"
    },
    "Bangladesh":{
        "en":"Bangladesh",
        "de":"Bangladesch",
        "ru":"Бангладеш",
        "pt":"Bangladesh",
        "nl":"Bangladesh",
        "fr":"Bangladesh",
        "it":"Bangladesh",
        "es":"Bangladesh",
        "pl":"Bangladesz",
        "zh-cn":"孟加拉国"
    },
    "Barbados":{
        "en":"Barbados",
        "de":"Barbados",
        "ru":"Барбадос",
        "pt":"Barbados",
        "nl":"Barbados",
        "fr":"Barbade",
        "it":"Barbados",
        "es":"Barbados",
        "pl":"Barbados",
        "zh-cn":"巴巴多斯"
    },
    "Belarus":{
        "en":"Belarus",
        "de":"Belarus",
        "ru":"Беларусь",
        "pt":"Bielorrússia",
        "nl":"Wit-Rusland",
        "fr":"Biélorussie",
        "it":"Bielorussia",
        "es":"Bielorrusia",
        "pl":"Białoruś",
        "zh-cn":"白俄罗斯"
    },
    "Belgium":{
        "en":"Belgium",
        "de":"Belgien",
        "ru":"Бельгия",
        "pt":"Bélgica",
        "nl":"België",
        "fr":"Belgique",
        "it":"Belgio",
        "es":"Bélgica",
        "pl":"Belgia",
        "zh-cn":"比利时"
    },
    "Belize":{
        "en":"Belize",
        "de":"Belize",
        "ru":"Белиз",
        "pt":"Belize",
        "nl":"Belize",
        "fr":"Belize",
        "it":"Belize",
        "es":"Belice",
        "pl":"Belize",
        "zh-cn":"伯利兹"
    },
    "Benin":{
        "en":"Benin",
        "de":"Benin",
        "ru":"Бенин",
        "pt":"Benim",
        "nl":"Benin",
        "fr":"Bénin",
        "it":"Benin",
        "es":"Benin",
        "pl":"Benin",
        "zh-cn":"贝宁"
    },
    "Bermuda":{
        "en":"Bermuda",
        "de":"Bermuda",
        "ru":"Бермуды",
        "pt":"Bermudas",
        "nl":"Bermuda",
        "fr":"Bermudes",
        "it":"Bermuda",
        "es":"Bermudas",
        "pl":"Bermudy",
        "zh-cn":"百慕大"
    },
    "Bhutan":{
        "en":"Bhutan",
        "de":"Bhutan",
        "ru":"Бутан",
        "pt":"Butão",
        "nl":"Bhutan",
        "fr":"Bhoutan",
        "it":"Bhutan",
        "es":"Bután",
        "pl":"Bhutan",
        "zh-cn":"不丹"
    },
    "Bolivia":{
        "en":"Bolivia",
        "de":"Bolivien",
        "ru":"Боливия",
        "pt":"Bolívia",
        "nl":"Bolivië",
        "fr":"Bolivie",
        "it":"Bolivia",
        "es":"Bolivia",
        "pl":"Boliwia",
        "zh-cn":"玻利维亚"
    },
    "Bosnia and Herzegovina":{
        "en":"Bosnia and Herzegovina",
        "de":"Bosnien und Herzegowina",
        "ru":"Босния и Герцеговина",
        "pt":"Bósnia-Herzegovina",
        "nl":"Bosnië-Herzegovina",
        "fr":"Bosnie-Herzégovine",
        "it":"Bosnia ed Erzegovina",
        "es":"Bosnia y Herzegovina",
        "pl":"Bośnia i Hercegowina",
        "zh-cn":"波黑"
    },
    "Botswana":{
        "en":"Botswana",
        "de":"Botswana",
        "ru":"Ботсвана",
        "pt":"Botsuana",
        "nl":"Botswana",
        "fr":"Botswana",
        "it":"Botswana",
        "es":"Botswana",
        "pl":"Botswana",
        "zh-cn":"博 茨瓦纳"
    },
    "Bouvet Island":{
        "en":"Bouvet Island",
        "de":"Bouvetinsel",
        "ru":"Остров Буве",
        "pt":"Ilha Bouvet",
        "nl":"Bouvet Eiland",
        "fr":"Île Bouvet",
        "it":"Isola Bouvet",
        "es":"Isla Bouvet",
        "pl":"Wyspa Bouveta",
        "zh-cn":"布韦岛"
    },
    "Brazil":{
        "en":"Brazil",
        "de":"Brasilien",
        "ru":"Бразилия",
        "pt":"Brasil",
        "nl":"Brazilië",
        "fr":"Brésil",
        "it":"Brasile",
        "es":"Brasil",
        "pl":"Brazylia",
        "zh-cn":"巴西"
    },
    "British Indian Ocean Territory":{
        "en":"British Indian Ocean Territory",
        "de":"Britisches Territorium im Indischen Ozean",
        "ru":"Британская территория в Индийском океане",
        "pt":"Território Britânico do Oceano Índico",
        "nl":"Brits Indische oceaan",
        "fr":"Océan Indien Britannique",
        "it":"Territori Britannici dell'Oceano Indiano",
        "es":"Territorio Británico del Océano Índico",
        "pl":"Brytyjskie Terytorium Oceanu Indyjskiego",
        "zh-cn":"英属印度洋领地"
    },
    "Brunei Darussalam":{
        "en":"Brunei Darussalam",
        "de":"Brunei Darussalam",
        "ru":"Бруней",
        "pt":"Brunei",
        "nl":"Brunei Darussalam",
        "fr":"Brunei Darussalam",
        "it":"Brunei",
        "es":"Brunei Darussalam",
        "pl":"Brunei",
        "zh-cn":"文莱"
    },
    "Bulgaria":{
        "en":"Bulgaria",
        "de":"Bulgarien",
        "ru":"Болгария",
        "pt":"Bulgária",
        "nl":"Bulgarije",
        "fr":"Bulgarie",
        "it":"Bulgaria",
        "es":"Bulgaria",
        "pl":"Bułgaria",
        "zh-cn":"保加利亚"
    },
    "Burkina Faso":{
        "en":"Burkina Faso",
        "de":"Burkina Faso",
        "ru":"Буркина-Фасо",
        "pt":"Burkina Faso",
        "nl":"Burkina Faso",
        "fr":"Burkina Faso",
        "it":"Burkina Faso",
        "es":"Burkina Faso",
        "pl":"Burkina Faso",
        "zh-cn":" 布基纳法索"
    },
    "Burundi":{
        "en":"Burundi",
        "de":"Burundi",
        "ru":"Бурунди",
        "pt":"Burundi",
        "nl":"Burundi",
        "fr":"Burundi",
        "it":"Burundi",
        "es":"Burundi",
        "pl":"Burundi",
        "zh-cn":"布隆迪"
    },
    "Cambodia":{
        "en":"Cambodia",
        "de":"Kambodscha",
        "ru":"Камбоджа",
        "pt":"Camboja",
        "nl":"Cambodja",
        "fr":"Cambodge",
        "it":"Cambogia",
        "es":"Camboya",
        "pl":"Kambodża",
        "zh-cn":"柬埔寨"
    },
    "Cameroon":{
        "en":"Cameroon",
        "de":"Kamerun",
        "ru":"Камерун",
        "pt":"Camarões",
        "nl":"Kameroen",
        "fr":"Cameroun",
        "it":"Camerun",
        "es":"Camerún",
        "pl":"Kamerun",
        "zh-cn":"喀麦隆"
    },
    "Canada":{
        "en":"Canada",
        "de":"Kanada",
        "ru":"Канада",
        "pt":"Canadá",
        "nl":"Canada",
        "fr":"Canada",
        "it":"Canada",
        "es":"Canadá",
        "pl":"Kanada",
        "zh-cn":"加拿大"
    },
    "Cape Verde":{
        "en":"Cape Verde",
        "de":"Kap Verde",
        "ru":"Кабо-Верде",
        "pt":"Cabo Verde",
        "nl":"Kaapverdië",
        "fr":"Cap-Vert",
        "it":"Capo Verde",
        "es":"Cabo Verde",
        "pl":"Republika Zielonego Przylądka",
        "zh-cn":"佛得角"
    },
    "Cayman Islands":{
        "en":"Cayman Islands",
        "de":"Kaimaninseln",
        "ru":"Острова Кайман",
        "pt":"Ilhas Caimão",
        "nl":"Kaaimaneilanden",
        "fr":"Îles Caïmans",
        "it":"Isole Cayman",
        "es":"Islas Caimán",
        "pl":"Kajmany",
        "zh-cn":"开曼群岛"
    },
    "Central African Republic":{
        "en":"Central African Republic",
        "de":"Zentralafrikanische Republik",
        "ru":"ЦАР",
        "pt":"República Centro-Africana",
        "nl":"Centraal-Afrikaanse Republiek",
        "fr":"République Centrafricaine",
        "it":"Repubblica Centrafricana",
        "es":"República Centroafricana",
        "pl":"Republika Środkowoafrykańska",
        "zh-cn":"中 非"
    },
    "Chad":{
        "en":"Chad",
        "de":"Tschad",
        "ru":"Чад",
        "pt":"Chade",
        "nl":"Tsjaad",
        "fr":"Tchad",
        "it":"Ciad",
        "es":"Chad",
        "pl":"Czad",
        "zh-cn":"乍得"
    },
    "Chile":{
        "en":"Chile",
        "de":"Chile",
        "ru":"Чили",
        "pt":"Chile",
        "nl":"Chili",
        "fr":"Chili",
        "it":"Cile",
        "es":"Chile",
        "pl":"Chile",
        "zh-cn":"智利"
    },
    "People's Republic of China":{
        "en":"People's Republic of China",
        "de":"China",
        "ru":"КНР (Китайская Народная Республика)",
        "pt":"China",
        "nl":"China",
        "fr":"Chine",
        "it":"Cina",
        "es":"China",
        "pl":"Chiny",
        "zh-cn":"中国"
    },
    "Christmas Island":{
        "en":"Christmas Island",
        "de":"Weihnachtsinsel",
        "ru":"Остров Рождества",
        "pt":"Ilha de Natal",
        "nl":"Christmaseiland",
        "fr":"Île Christmas",
        "it":"Isola del Natale",
        "es":"Isla de Navidad",
        "pl":"Wyspa Bożego Narodzenia",
        "zh-cn":"圣诞岛"
    },
    "Cocos (Keeling) Islands":{
        "en":"Cocos (Keeling) Islands",
        "de":"Kokosinseln",
        "ru":"Кокосовые острова",
        "pt":"Ilhas Cocos (Keeling)",
        "nl":"Cocoseilanden",
        "fr":"Îles Cocos",
        "it":"Isole Cocos e Keeling",
        "es":"Islas Cocos (Keeling)",
        "pl":"Wyspy Kokosowe",
        "zh-cn":"科科斯（基林）群岛"
    },
    "Colombia":{
        "en":"Colombia",
        "de":"Kolumbien",
        "ru":"Колумбия",
        "pt":"Colômbia",
        "nl":"Colombia",
        "fr":"Colombie",
        "it":"Colombia",
        "es":"Colombia",
        "pl":"Kolumbia",
        "zh-cn":"哥伦比亚"
    },
    "Comoros":{
        "en":"Comoros",
        "de":"Komoren",
        "ru":"Коморы",
        "pt":"Comores",
        "nl":"Comoren",
        "fr":"Comores",
        "it":"Comore",
        "es":"Comoras",
        "pl":"Komory",
        "zh-cn":"科摩罗"
    },
    "Republic of the Congo":{
        "en":"Republic of the Congo",
        "de":"Republik Kongo",
        "ru":"Республика Конго",
        "pt":"República Democrática do Congo",
        "nl":"Congo, Volksrepubliek",
        "fr":"République du Congo",
        "it":"Repubblica del Congo",
        "es":"Congo",
        "pl":"Kongo",
        "zh-cn":"刚果（布）"
    },
    "Democratic Republic of the Congo":{
        "en":"Democratic Republic of the Congo",
        "de":"Kongo",
        "ru":"Демократическая Республика Конго",
        "pt":"República Popular do Congo",
        "nl":"Congo, Democratische Republiek",
        "fr":"République démocratique du Congo",
        "it":"Repubblica Democratica del Congo",
        "es":"Congo (República Democrática del)",
        "pl":"Demokratyczna Republika Konga",
        "zh-cn":"刚果（金）"
    },
    "Cook Islands":{
        "en":"Cook Islands",
        "de":"Cookinseln",
        "ru":"Острова Кука",
        "pt":"Ilhas Cook",
        "nl":"Cookeilanden",
        "fr":"Îles Cook",
        "it":"Isole Cook",
        "es":"Islas Cook",
        "pl":"Wyspy Cooka",
        "zh-cn":"库克群岛"
    },
    "Costa Rica":{
        "en":"Costa Rica",
        "de":"Costa Rica",
        "ru":"Коста-Рика",
        "pt":"Costa Rica",
        "nl":"Costa Rica",
        "fr":"Costa Rica",
        "it":"Costa Rica",
        "es":"Costa Rica",
        "pl":"Kostaryka",
        "zh-cn":"哥斯达黎加"
    },
    "Cote d'Ivoire":{
        "en":"Cote d'Ivoire",
        "de":"Elfenbeinküste",
        "ru":"Кот-д’Ивуар",
        "pt":"Costa do Marfim",
        "nl":"Ivoorkust",
        "fr":"Côte-d'Ivoire",
        "it":"Costa d'Avorio",
        "es":"Costa de Marfil",
        "pl":"Wybrzeże Kości Słoniowej",
        "zh-cn":"科特迪瓦"
    },
    "Croatia":{
        "en":"Croatia",
        "de":"Kroatien",
        "ru":"Хорватия",
        "pt":"Croácia",
        "nl":"Kroatië",
        "fr":"Croatie",
        "it":"Croazia",
        "es":"Croacia",
        "pl":"Chorwacja",
        "zh-cn":"克罗地亚"
    },
    "Cuba":{
        "en":"Cuba",
        "de":"Kuba",
        "ru":"Куба",
        "pt":"Cuba",
        "nl":"Cuba",
        "fr":"Cuba",
        "it":"Cuba",
        "es":"Cuba",
        "pl":"Kuba",
        "zh-cn":"古巴"
    },
    "Cyprus":{
        "en":"Cyprus",
        "de":"Zypern",
        "ru":"Кипр",
        "pt":"Chipre",
        "nl":"Cyprus",
        "fr":"Chypre",
        "it":"Cipro",
        "es":"Chipre",
        "pl":"Cypr",
        "zh-cn":"塞浦路斯"
    },
    "Czech Republic":{
        "en":"Czech Republic",
        "de":"Tschechische Republik",
        "ru":"Чехия",
        "pt":"Chéquia",
        "nl":"Tsjechië",
        "fr":"République Tchèque",
        "it":"Repubblica Ceca",
        "es":"República Checa",
        "pl":"Czechy",
        "zh-cn":"捷克"
    },
    "Denmark":{
        "en":"Denmark",
        "de":"Dänemark",
        "ru":"Дания",
        "pt":"Dinamarca",
        "nl":"Denemarken",
        "fr":"Danemark",
        "it":"Danimarca",
        "es":"Dinamarca",
        "pl":"Dania",
        "zh-cn":"丹麦"
    },
    "Djibouti":{
        "en":"Djibouti",
        "de":"Dschibuti",
        "ru":"Джибути",
        "pt":"Djibouti",
        "nl":"Djibouti",
        "fr":"Djibouti",
        "it":"Gibuti",
        "es":"Yibuti",
        "pl":"Dżibuti",
        "zh-cn":"吉布提"
    },
    "Dominica":{
        "en":"Dominica",
        "de":"Dominica",
        "ru":"Доминика",
        "pt":"Dominica",
        "nl":"Dominica",
        "fr":"Dominique",
        "it":"Dominica",
        "es":"Dominica",
        "pl":"Dominika",
        "zh-cn":"多米尼克"
    },
    "Dominican Republic":{
        "en":"Dominican Republic",
        "de":"Dominikanische Republik",
        "ru":"Доминиканская Республика",
        "pt":"República Dominicana",
        "nl":"Dominicaanse Republiek",
        "fr":"République Dominicaine",
        "it":"Repubblica Dominicana",
        "es":"República Dominicana",
        "pl":"Dominikana",
        "zh-cn":"多米尼加"
    },
    "Ecuador":{
        "en":"Ecuador",
        "de":"Ecuador",
        "ru":"Эквадор",
        "pt":"Equador",
        "nl":"Ecuador",
        "fr":"Équateur",
        "it":"Ecuador",
        "es":"Ecuador",
        "pl":"Ekwador",
        "zh-cn":"厄瓜多尔"
    },
    "Egypt":{
        "en":"Egypt",
        "de":"Ägypten",
        "ru":"Египет",
        "pt":"Egito",
        "nl":"Egypte",
        "fr":"Égypte",
        "it":"Egitto",
        "es":"Egipto",
        "pl":"Egipt",
        "zh-cn":"埃及"
    },
    "El Salvador":{
        "en":"El Salvador",
        "de":"El Salvador",
        "ru":"Сальвадор",
        "pt":"El Salvador",
        "nl":"El Salvador",
        "fr":"El Salvador",
        "it":"El Salvador",
        "es":"El Salvador",
        "pl":"Salwador",
        "zh-cn":"萨尔瓦多"
    },
    "Equatorial Guinea":{
        "en":"Equatorial Guinea",
        "de":"Äquatorialguinea",
        "ru":"Экваториальная Гвинея",
        "pt":"Guiné Equatorial",
        "nl":"Equatoriaal-Guinea",
        "fr":"Guinée équatoriale",
        "it":"Guinea Equatoriale",
        "es":"Guinea Ecuatorial",
        "pl":"Gwinea Równikowa",
        "zh-cn":"赤道几内亚"
    },
    "Eritrea":{
        "en":"Eritrea",
        "de":"Eritrea",
        "ru":"Эритрея",
        "pt":"Eritreia",
        "nl":"Eritrea",
        "fr":"Érythrée",
        "it":"Eritrea",
        "es":"Eritrea",
        "pl":"Erytrea",
        "zh-cn":"厄立特里亚"
    },
    "Estonia":{
        "en":"Estonia",
        "de":"Estland",
        "ru":"Эстония",
        "pt":"Estónia",
        "nl":"Estland",
        "fr":"Estonie",
        "it":"Estonia",
        "es":"Estonia",
        "pl":"Estonia",
        "zh-cn":"爱沙尼亚"
    },
    "Ethiopia":{
        "en":"Ethiopia",
        "de":"Äthiopien",
        "ru":"Эфиопия",
        "pt":"Etiópia",
        "nl":"Ethiopië",
        "fr":"Éthiopie",
        "it":"Etiopia",
        "es":"Etiopía",
        "pl":"Etiopia",
        "zh-cn":"埃塞俄比亚"
    },
    "Falkland Islands (Malvinas)":{
        "en":"Falkland Islands (Malvinas)",
        "de":"Falklandinseln",
        "ru":"Фолклендские острова",
        "pt":"Ilhas Malvinas",
        "nl":"Falklandeilanden",
        "fr":"Îles Malouines",
        "it":"Isole Falkland",
        "es":"Islas Malvinas",
        "pl":"Falklandy",
        "zh-cn":"福克兰群岛"
    },
    "Faroe Islands":{
        "en":"Faroe Islands",
        "de":"Färöer",
        "ru":"Фареры",
        "pt":"Ilhas Faroé",
        "nl":"Faeröer",
        "fr":"Îles Féroé",
        "it":"Isole Fær Øer",
        "es":"Islas Feroe",
        "pl":"Wyspy Owcze",
        "zh-cn":"法罗群岛"
    },
    "Fiji":{
        "en":"Fiji",
        "de":"Fidschi",
        "ru":"Фиджи",
        "pt":"Fiji",
        "nl":"Fiji",
        "fr":"Fidji",
        "it":"Figi",
        "es":"Fiji",
        "pl":"Fidżi",
        "zh-cn":"斐济"
    },
    "Finland":{
        "en":"Finland",
        "de":"Finnland",
        "ru":"Финляндия",
        "pt":"Finlândia",
        "nl":"Finland",
        "fr":"Finlande",
        "it":"Finlandia",
        "es":"Finlandia",
        "pl":"Finlandia",
        "zh-cn":"芬兰"
    },
    "France":{
        "en":"France",
        "de":"Frankreich",
        "ru":"Франция",
        "pt":"França",
        "nl":"Frankrijk",
        "fr":"France",
        "it":"Francia",
        "es":"Francia",
        "pl":"Francja",
        "zh-cn":"法国"
    },
    "French Guiana":{
        "en":"French Guiana",
        "de":"Französisch-Guayana",
        "ru":"Гвиана",
        "pt":"Guiana Francesa",
        "nl":"Frans-Guyana",
        "fr":"Guyane française",
        "it":"Guyana Francese",
        "es":"Guayana Francesa",
        "pl":"Gujana Francuska",
        "zh-cn":"法属圭亚那"
    },
    "French Polynesia":{
        "en":"French Polynesia",
        "de":"Französisch-Polynesien",
        "ru":"Французская Полинезия",
        "pt":"Polinésia Francesa",
        "nl":"Frans-Polynesië",
        "fr":"Polynésie française",
        "it":"Polinesia Francese",
        "es":"Polinesia Francesa",
        "pl":"Polinezja Francuska",
        "zh-cn":"法属波利尼西亚"
    },
    "French Southern Territories":{
        "en":"French Southern Territories",
        "de":"Französische Süd- und Antarktisgebiete",
        "ru":"Французские Южные и Антарктические Территории",
        "pt":"Terras Austrais e Antárticas Francesas",
        "nl":"Franse Zuidelijke Gebieden",
        "fr":"Terres australes françaises",
        "it":"Territori Francesi del Sud",
        "es":"Tierras Australes Francesas",
        "pl":"Francuskie Terytoria Południowe i Antarktyczne",
        "zh-cn":"法属南部领地"
    },
    "Gabon":{
        "en":"Gabon",
        "de":"Gabun",
        "ru":"Габон",
        "pt":"Gabão",
        "nl":"Gabon",
        "fr":"Gabon",
        "it":"Gabon",
        "es":"Gabón",
        "pl":"Gabon",
        "zh-cn":"加蓬"
    },
    "Republic of The Gambia":{
        "en":"Republic of The Gambia",
        "de":"Gambia",
        "ru":"Гамбия",
        "pt":"Gâmbia",
        "nl":"Gambia",
        "fr":"Gambie",
        "it":"Gambia",
        "es":"Gambia",
        "pl":"Gambia",
        "zh-cn":"冈比亚"
    },
    "Georgia":{
        "en":"Georgia",
        "de":"Georgien",
        "ru":"Грузия",
        "pt":"Geórgia",
        "nl":"Georgië",
        "fr":"Géorgie",
        "it":"Georgia",
        "es":"Georgia",
        "pl":"Gruzja",
        "zh-cn":"格鲁吉亚"
    },
    "Germany":{
        "en":"Germany",
        "de":"Deutschland",
        "ru":"Германия",
        "pt":"Alemanha",
        "nl":"Duitsland",
        "fr":"Allemagne",
        "it":"Germania",
        "es":"Alemania",
        "pl":"Niemcy",
        "zh-cn":"德国"
    },
    "Ghana":{
        "en":"Ghana",
        "de":"Ghana",
        "ru":"Гана",
        "pt":"Gana",
        "nl":"Ghana",
        "fr":"Ghana",
        "it":"Ghana",
        "es":"Ghana",
        "pl":"Ghana",
        "zh-cn":"加纳"
    },
    "Gibraltar":{
        "en":"Gibraltar",
        "de":"Gibraltar",
        "ru":"Гибралтар",
        "pt":"Gibraltar",
        "nl":"Gibraltar",
        "fr":"Gibraltar",
        "it":"Gibilterra",
        "es":"Gibraltar",
        "pl":"Gibraltar",
        "zh-cn":"直布罗陀"
    },
    "Greece":{
        "en":"Greece",
        "de":"Griechenland",
        "ru":"Греция",
        "pt":"Grécia",
        "nl":"Griekenland",
        "fr":"Grèce",
        "it":"Grecia",
        "es":"Grecia",
        "pl":"Grecja",
        "zh-cn":"希腊"
    },
    "Greenland":{
        "en":"Greenland",
        "de":"Grönland",
        "ru":"Гренландия",
        "pt":"Gronelândia",
        "nl":"Groenland",
        "fr":"Groenland",
        "it":"Groenlandia",
        "es":"Groenlandia",
        "pl":"Grenlandia",
        "zh-cn":"格陵兰"
    },
    "Grenada":{
        "en":"Grenada",
        "de":"Grenada",
        "ru":"Гренада",
        "pt":"Granada",
        "nl":"Grenada",
        "fr":"Grenade",
        "it":"Grenada",
        "es":"Granada",
        "pl":"Grenada",
        "zh-cn":"格林纳达"
    },
    "Guadeloupe":{
        "en":"Guadeloupe",
        "de":"Guadeloupe",
        "ru":"Гваделупа",
        "pt":"Guadalupe",
        "nl":"Guadeloupe",
        "fr":"Guadeloupe",
        "it":"Guadalupa",
        "es":"Guadalupe",
        "pl":"Gwadelupa",
        "zh-cn":"瓜德罗普"
    },
    "Guam":{
        "en":"Guam",
        "de":"Guam",
        "ru":"Гуам",
        "pt":"Guam",
        "nl":"Guam",
        "fr":"Guam",
        "it":"Guam",
        "es":"Guam",
        "pl":"Guam",
        "zh-cn":" 关岛"
    },
    "Guatemala":{
        "en":"Guatemala",
        "de":"Guatemala",
        "ru":"Гватемала",
        "pt":"Guatemala",
        "nl":"Guatemala",
        "fr":"Guatemala",
        "it":"Guatemala",
        "es":"Guatemala",
        "pl":"Gwatemala",
        "zh-cn":"危地马拉"
    },
    "Guinea":{
        "en":"Guinea",
        "de":"Guinea",
        "ru":"Гвинея",
        "pt":"Guiné",
        "nl":"Guinea",
        "fr":"Guinée",
        "it":"Guinea",
        "es":"Guinea",
        "pl":"Gwinea",
        "zh-cn":"几内亚"
    },
    "Guinea-Bissau":{
        "en":"Guinea-Bissau",
        "de":"Guinea-Bissau",
        "ru":"Гвинея-Бисау",
        "pt":"Guiné-Bissau",
        "nl":"Guinee-Bissau",
        "fr":"Guinée-Bissau",
        "it":"Guinea-Bissau",
        "es":"Guinea Bissau",
        "pl":"Gwinea Bissau",
        "zh-cn":"几内亚比绍"
    },
    "Guyana":{
        "en":"Guyana",
        "de":"Guyana",
        "ru":"Гайана",
        "pt":"Guiana",
        "nl":"Guyana",
        "fr":"Guyana",
        "it":"Guyana",
        "es":"Guyana",
        "pl":"Gujana",
        "zh-cn":"圭亚那"
    },
    "Haiti":{
        "en":"Haiti",
        "de":"Haiti",
        "ru":"Гаити",
        "pt":"Haiti",
        "nl":"Haïti",
        "fr":"Haïti",
        "it":"Haiti",
        "es":"Haití",
        "pl":"Haiti",
        "zh-cn":"海地"
    },
    "Heard Island and McDonald Islands":{
        "en":"Heard Island and McDonald Islands",
        "de":"Heard und McDonaldinseln",
        "ru":"Херд и Макдональд",
        "pt":"Ilha Heard e Ilhas McDonald",
        "nl":"Heard en McDonaldeilanden",
        "fr":"Îles Heard-et-MacDonald",
        "it":"Isole Heard e McDonald",
        "es":"Heard e Islas McDonald",
        "pl":"Wyspy Heard i McDonalda",
        "zh-cn":"赫德岛和麦克唐纳群岛"
    },
    "Holy See (Vatican City State)":{
        "en":"Holy See (Vatican City State)",
        "de":"Vatikanstadt",
        "ru":"Ватикан",
        "pt":"Santa Sé",
        "nl":"Heilige Stoel",
        "fr":"Saint-Siège (Vatican)",
        "it":"Città del Vaticano",
        "es":"Santa Sede",
        "pl":"Watykan",
        "zh-cn":"梵蒂冈"
    },
    "Honduras":{
        "en":"Honduras",
        "de":"Honduras",
        "ru":"Гондурас",
        "pt":"Honduras",
        "nl":"Honduras",
        "fr":"Honduras",
        "it":"Honduras",
        "es":"Honduras",
        "pl":"Honduras",
        "zh-cn":"洪都拉斯"
    },
    "Hong Kong":{
        "en":"Hong Kong",
        "de":"Hongkong",
        "ru":"Гонконг",
        "pt":"Hong Kong",
        "nl":"Hong Kong",
        "fr":"Hong Kong",
        "it":"Hong Kong",
        "es":"Hong Kong",
        "pl":"Hongkong",
        "zh-cn":"香港"
    },
    "Hungary":{
        "en":"Hungary",
        "de":"Ungarn",
        "ru":"Венгрия",
        "pt":"Hungria",
        "nl":"Hongarije",
        "fr":"Hongrie",
        "it":"Ungheria",
        "es":"Hungría",
        "pl":"Węgry",
        "zh-cn":"匈牙利"
    },
    "Iceland":{
        "en":"Iceland",
        "de":"Island",
        "ru":"Исландия",
        "pt":"Islândia",
        "nl":"IJsland",
        "fr":"Islande",
        "it":"Islanda",
        "es":"Islandia",
        "pl":"Islandia",
        "zh-cn":"冰岛"
    },
    "India":{
        "en":"India",
        "de":"Indien",
        "ru":"Индия",
        "pt":"Índia",
        "nl":"India",
        "fr":"Inde",
        "it":"India",
        "es":"India",
        "pl":"Indie",
        "zh-cn":"印度"
    },
    "Indonesia":{
        "en":"Indonesia",
        "de":"Indonesien",
        "ru":"Индонезия",
        "pt":"Indonésia",
        "nl":"Indonesië",
        "fr":"Indonésie",
        "it":"Indonesia",
        "es":"Indonesia",
        "pl":"Indonezja",
        "zh-cn":"印尼"
    },
    "Islamic Republic of Iran":{
        "en":"Islamic Republic of Iran",
        "de":"Iran",
        "ru":"Иран",
        "pt":"Irão",
        "nl":"Iran",
        "fr":"Iran",
        "it":"Iran",
        "es":"Irán",
        "pl":"Iran",
        "zh-cn":"伊朗"
    },
    "Iraq":{
        "en":"Iraq",
        "de":"Irak",
        "ru":"Ирак",
        "pt":"Iraque",
        "nl":"Irak",
        "fr":"Irak",
        "it":"Iraq",
        "es":"Iraq",
        "pl":"Irak",
        "zh-cn":"伊拉克"
    },
    "Ireland":{
        "en":"Ireland",
        "de":"Irland",
        "ru":"Ирландия",
        "pt":"Irlanda",
        "nl":"Ierland",
        "fr":"Irlande",
        "it":"Irlanda",
        "es":"Irlanda",
        "pl":"Irlandia",
        "zh-cn":"爱尔兰"
    },
    "Israel":{
        "en":"Israel",
        "de":"Israel",
        "ru":"Израиль",
        "pt":"Israel",
        "nl":"Israël",
        "fr":"Israël",
        "it":"Israele",
        "es":"Israel",
        "pl":"Izrael",
        "zh-cn":"以色列"
    },
    "Italy":{
        "en":"Italy",
        "de":"Italien",
        "ru":"Италия",
        "pt":"Itália",
        "nl":"Italië",
        "fr":"Italie",
        "it":"Italia",
        "es":"Italia",
        "pl":"Włochy",
        "zh-cn":"意大利"
    },
    "Jamaica":{
        "en":"Jamaica",
        "de":"Jamaika",
        "ru":"Ямайка",
        "pt":"Jamaica",
        "nl":"Jamaica",
        "fr":"Jamaïque",
        "it":"Giamaica",
        "es":"Jamaica",
        "pl":"Jamajka",
        "zh-cn":"牙买加"
    },
    "Japan":{
        "en":"Japan",
        "de":"Japan",
        "ru":"Япония",
        "pt":"Japão",
        "nl":"Japan",
        "fr":"Japon",
        "it":"Giappone",
        "es":"Japón",
        "pl":"Japonia",
        "zh-cn":"日本"
    },
    "Jordan":{
        "en":"Jordan",
        "de":"Jordanien",
        "ru":"Иордания",
        "pt":"Jordânia",
        "nl":"Jordanië",
        "fr":"Jordanie",
        "it":"Giordania",
        "es":"Jordania",
        "pl":"Jordania",
        "zh-cn":"约旦"
    },
    "Kazakhstan":{
        "en":"Kazakhstan",
        "de":"Kasachstan",
        "ru":"Казахстан",
        "pt":"Cazaquistão",
        "nl":"Kazachstan",
        "fr":"Kazakhstan",
        "it":"Kazakistan",
        "es":"Kazajistán",
        "pl":"Kazachstan",
        "zh-cn":"哈萨克斯坦"
    },
    "Kenya":{
        "en":"Kenya",
        "de":"Kenia",
        "ru":"Кения",
        "pt":"Quénia",
        "nl":"Kenia",
        "fr":"Kenya",
        "it":"Kenya",
        "es":"Kenia",
        "pl":"Kenia",
        "zh-cn":"肯尼亚"
    },
    "Kiribati":{
        "en":"Kiribati",
        "de":"Kiribati",
        "ru":"Кирибати",
        "pt":"Quiribati",
        "nl":"Kiribati",
        "fr":"Kiribati",
        "it":"Kiribati",
        "es":"Kiribati",
        "pl":"Kiribati",
        "zh-cn":"基里巴斯"
    },
    "North Korea":{
        "en":"North Korea",
        "de":"Nordkorea",
        "ru":"КНДР (Корейская Народно-Демократическая Республика)",
        "pt":"Coreia do Norte",
        "nl":"Noord-Korea",
        "fr":"Corée du Nord",
        "it":"Corea del Nord",
        "es":"República Popular Democrática de Corea",
        "pl":"Korea Północna",
        "zh-cn":"朝鲜"
    },
    "South Korea":{
        "en":"South Korea",
        "de":"Südkorea",
        "ru":"Республика Корея",
        "pt":"Coreia do Sul",
        "nl":"Zuid-Korea",
        "fr":"Corée du Sud",
        "it":"Corea del Sud",
        "es":"República de Corea",
        "pl":"Korea Południowa",
        "zh-cn":"韩国"
    },
    "Kuwait":{
        "en":"Kuwait",
        "de":"Kuwait",
        "ru":"Кувейт",
        "pt":"Koweit",
        "nl":"Koeweit",
        "fr":"Koweït",
        "it":"Kuwait",
        "es":"Kuwait",
        "pl":"Kuwejt",
        "zh-cn":"科威特"
    },
    "Kyrgyzstan":{
        "en":"Kyrgyzstan",
        "de":"Kirgisistan",
        "ru":"Киргизия",
        "pt":"Quirguistão",
        "nl":"Kirgizstan",
        "fr":"Kirghizistan",
        "it":"Kirghizistan",
        "es":"Kirguistán",
        "pl":"Kirgistan",
        "zh-cn":"吉尔吉斯斯坦"
    },
    "Lao People's Democratic Republic":{
        "en":"Lao People's Democratic Republic",
        "de":"Laos",
        "ru":"Лаос",
        "pt":"Laos",
        "nl":"Laos",
        "fr":"Laos",
        "it":"Laos",
        "es":"República Democrática Popular de Lao",
        "pl":"Laos",
        "zh-cn":"老挝"
    },
    "Latvia":{
        "en":"Latvia",
        "de":"Lettland",
        "ru":"Латвия",
        "pt":"Letónia",
        "nl":"Letland",
        "fr":"Lettonie",
        "it":"Lettonia",
        "es":"Letonia",
        "pl":"Łotwa",
        "zh-cn":"拉脱维亚"
    },
    "Lebanon":{
        "en":"Lebanon",
        "de":"Libanon",
        "ru":"Ливан",
        "pt":"Líbano",
        "nl":"Libanon",
        "fr":"Liban",
        "it":"Libano",
        "es":"Líbano",
        "pl":"Liban",
        "zh-cn":"黎巴嫩"
    },
    "Lesotho":{
        "en":"Lesotho",
        "de":"Lesotho",
        "ru":"Лесото",
        "pt":"Lesoto",
        "nl":"Lesotho",
        "fr":"Lesotho",
        "it":"Lesotho",
        "es":"Lesoto",
        "pl":"Lesotho",
        "zh-cn":"莱索托"
    },
    "Liberia":{
        "en":"Liberia",
        "de":"Liberia",
        "ru":"Либерия",
        "pt":"Libéria",
        "nl":"Liberia",
        "fr":"Libéria",
        "it":"Liberia",
        "es":"Liberia",
        "pl":"Liberia",
        "zh-cn":"利比里亚"
    },
    "Libya":{
        "en":"Libya",
        "de":"Libyen",
        "ru":"Ливия",
        "pt":"Líbia",
        "nl":"Libië",
        "fr":"Libye",
        "it":"Libia",
        "es":"Libia",
        "pl":"Libia",
        "zh-cn":"利比亚"
    },
    "Liechtenstein":{
        "en":"Liechtenstein",
        "de":"Liechtenstein",
        "ru":"Лихтенштейн",
        "pt":"Liechtenstein",
        "nl":"Liechtenstein",
        "fr":"Liechtenstein",
        "it":"Liechtenstein",
        "es":"Liechtenstein",
        "pl":"Liechtenstein",
        "zh-cn":"列支敦士登"
    },
    "Lithuania":{
        "en":"Lithuania",
        "de":"Litauen",
        "ru":"Литва",
        "pt":"Lituânia",
        "nl":"Litouwen",
        "fr":"Lituanie",
        "it":"Lituania",
        "es":"Lituania",
        "pl":"Litwa",
        "zh-cn":"立陶宛"
    },
    "Luxembourg":{
        "en":"Luxembourg",
        "de":"Luxemburg",
        "ru":"Люксембург",
        "pt":"Luxemburgo",
        "nl":"Luxemburg",
        "fr":"Luxembourg",
        "it":"Lussemburgo",
        "es":"Luxemburgo",
        "pl":"Luksemburg",
        "zh-cn":"卢森堡"
    },
    "Macao":{
        "en":"Macao",
        "de":"Macao",
        "ru":"Макао",
        "pt":"Macau",
        "nl":"Macao",
        "fr":"Macao",
        "it":"Macao",
        "es":"Macao",
        "pl":"Makau",
        "zh-cn":"澳门"
    },
    "Madagascar":{
        "en":"Madagascar",
        "de":"Madagaskar",
        "ru":"Мадагаскар",
        "pt":"Madagáscar",
        "nl":"Madagaskar",
        "fr":"Madagascar",
        "it":"Madagascar",
        "es":"Madagascar",
        "pl":"Madagaskar",
        "zh-cn":"马达加斯加"
    },
    "Malawi":{
        "en":"Malawi",
        "de":"Malawi",
        "ru":"Малави",
        "pt":"Maláui",
        "nl":"Malawi",
        "fr":"Malawi",
        "it":"Malawi",
        "es":"Malaui",
        "pl":"Malawi",
        "zh-cn":"马拉维"
    },
    "Malaysia":{
        "en":"Malaysia",
        "de":"Malaysia",
        "ru":"Малайзия",
        "pt":"Malásia",
        "nl":"Maleisië",
        "fr":"Malaisie",
        "it":"Malesia",
        "es":"Malasia",
        "pl":"Malezja",
        "zh-cn":"马来西亚"
    },
    "Maldives":{
        "en":"Maldives",
        "de":"Malediven",
        "ru":"Мальдивы",
        "pt":"Maldivas",
        "nl":"Maldiven",
        "fr":"Maldives",
        "it":"Maldive",
        "es":"Maldivas",
        "pl":"Malediwy",
        "zh-cn":"马尔代夫"
    },
    "Mali":{
        "en":"Mali",
        "de":"Mali",
        "ru":"Мали",
        "pt":"Mali",
        "nl":"Mali",
        "fr":"Mali",
        "it":"Mali",
        "es":"Malí",
        "pl":"Mali",
        "zh-cn":"马里"
    },
    "Malta":{
        "en":"Malta",
        "de":"Malta",
        "ru":"Мальта",
        "pt":"Malta",
        "nl":"Malta",
        "fr":"Malte",
        "it":"Malta",
        "es":"Malta",
        "pl":"Malta",
        "zh-cn":"马耳他"
    },
    "Marshall Islands":{
        "en":"Marshall Islands",
        "de":"Marshallinseln",
        "ru":"Маршалловы Острова",
        "pt":"Ilhas Marshall",
        "nl":"Marshalleilanden",
        "fr":"Îles Marshall",
        "it":"Isole Marshall",
        "es":"Islas Marshall",
        "pl":"Wyspy Marshalla",
        "zh-cn":"马绍尔群岛"
    },
    "Martinique":{
        "en":"Martinique",
        "de":"Martinique",
        "ru":"Мартиника",
        "pt":"Martinica",
        "nl":"Martinique",
        "fr":"Martinique",
        "it":"Martinica",
        "es":"Martinica",
        "pl":"Martynika",
        "zh-cn":"马提尼克"
    },
    "Mauritania":{
        "en":"Mauritania",
        "de":"Mauretanien",
        "ru":"Мавритания",
        "pt":"Mauritânia",
        "nl":"Mauritanië",
        "fr":"Mauritanie",
        "it":"Mauritania",
        "es":"Mauritania",
        "pl":"Mauretania",
        "zh-cn":"毛里塔尼亚"
    },
    "Mauritius":{
        "en":"Mauritius",
        "de":"Mauritius",
        "ru":"Маврикий",
        "pt":"Maurícia",
        "nl":"Mauritius",
        "fr":"Maurice",
        "it":"Mauritius",
        "es":"Mauricio",
        "pl":"Mauritius",
        "zh-cn":"毛里求斯"
    },
    "Mayotte":{
        "en":"Mayotte",
        "de":"Mayotte",
        "ru":"Майотта",
        "pt":"Mayotte",
        "nl":"Mayotte",
        "fr":"Mayotte",
        "it":"Mayotte",
        "es":"Mayotte",
        "pl":"Majotta",
        "zh-cn":"马约特"
    },
    "Mexico":{
        "en":"Mexico",
        "de":"Mexiko",
        "ru":"Мексика",
        "pt":"México",
        "nl":"Mexico",
        "fr":"Mexique",
        "it":"Messico",
        "es":"México",
        "pl":"Meksyk",
        "zh-cn":"墨西哥"
    },
    "Micronesia, Federated States of":{
        "en":"Micronesia, Federated States of",
        "de":"Mikronesien",
        "ru":"Микронезия",
        "pt":"Micronésia",
        "nl":"Micronesië, Federale Staten",
        "fr":"Micronésie",
        "it":"Stati Federati di Micronesia",
        "es":"Micronesia",
        "pl":"Mikronezja",
        "zh-cn":"密克罗尼西亚联邦"
    },
    "Moldova, Republic of":{
        "en":"Moldova, Republic of",
        "de":"Moldawien",
        "ru":"Молдавия",
        "pt":"Moldávia",
        "nl":"Moldavië",
        "fr":"Moldavie",
        "it":"Moldavia",
        "es":"Moldavia",
        "pl":"Mołdawia",
        "zh-cn":"摩尔多瓦"
    },
    "Monaco":{
        "en":"Monaco",
        "de":"Monaco",
        "ru":"Монако",
        "pt":"Mónaco",
        "nl":"Monaco",
        "fr":"Monaco",
        "it":"Monaco",
        "es":"Mónaco",
        "pl":"Monako",
        "zh-cn":"摩纳 哥"
    },
    "Mongolia":{
        "en":"Mongolia",
        "de":"Mongolei",
        "ru":"Монголия",
        "pt":"Mongólia",
        "nl":"Mongolië",
        "fr":"Mongolie",
        "it":"Mongolia",
        "es":"Mongolia",
        "pl":"Mongolia",
        "zh-cn":"蒙古"
    },
    "Montserrat":{
        "en":"Montserrat",
        "de":"Montserrat",
        "ru":"Монтсеррат",
        "pt":"Monserrate",
        "nl":"Montserrat",
        "fr":"Montserrat",
        "it":"Montserrat",
        "es":"Montserrat",
        "pl":"Montserrat",
        "zh-cn":"蒙特塞拉特"
    },
    "Morocco":{
        "en":"Morocco",
        "de":"Marokko",
        "ru":"Марокко",
        "pt":"Marrocos",
        "nl":"Marokko",
        "fr":"Maroc",
        "it":"Marocco",
        "es":"Marruecos",
        "pl":"Maroko",
        "zh-cn":"摩洛哥"
    },
    "Mozambique":{
        "en":"Mozambique",
        "de":"Mosambik",
        "ru":"Мозамбик",
        "pt":"Moçambique",
        "nl":"Mozambique",
        "fr":"Mozambique",
        "it":"Mozambico",
        "es":"Mozambique",
        "pl":"Mozambik",
        "zh-cn":"莫桑比克"
    },
    "Myanmar":{
        "en":"Myanmar",
        "de":"Myanmar",
        "ru":"Мьянма",
        "pt":"Mianmar (Birmânia)",
        "nl":"Myanmar",
        "fr":"Myanmar",
        "it":"Birmania  Myanmar",
        "es":"Myanmar",
        "pl":"Mjanma",
        "zh-cn":"缅甸"
    },
    "Namibia":{
        "en":"Namibia",
        "de":"Namibia",
        "ru":"Намибия",
        "pt":"Namíbia",
        "nl":"Namibië",
        "fr":"Namibie",
        "it":"Namibia",
        "es":"Namibia",
        "pl":"Namibia",
        "zh-cn":"纳米比亚"
    },
    "Nauru":{
        "en":"Nauru",
        "de":"Nauru",
        "ru":"Науру",
        "pt":"Nauru",
        "nl":"Nauru",
        "fr":"Nauru",
        "it":"Nauru",
        "es":"Nauru",
        "pl":"Nauru",
        "zh-cn":"瑙鲁"
    },
    "Nepal":{
        "en":"Nepal",
        "de":"Nepal",
        "ru":"Непал",
        "pt":"Nepal",
        "nl":"Nepal",
        "fr":"Népal",
        "it":"Nepal",
        "es":"Nepal",
        "pl":"Nepal",
        "zh-cn":"尼泊尔"
    },
    "Netherlands":{
        "en":"Netherlands",
        "de":"Niederlande",
        "ru":"Нидерланды",
        "pt":"Países Baixos",
        "nl":"Nederland",
        "fr":"Pays-Bas",
        "it":"Paesi Bassi",
        "es":"Países Bajos",
        "pl":"Holandia",
        "zh-cn":"荷兰"
    },
    "New Caledonia":{
        "en":"New Caledonia",
        "de":"Neukaledonien",
        "ru":"Новая Каледония",
        "pt":"Nova Caledónia",
        "nl":"Nieuw-Caledonië",
        "fr":"Nouvelle-Calédonie",
        "it":"Nuova Caledonia",
        "es":"Nueva Caledonia",
        "pl":"Nowa Kaledonia",
        "zh-cn":"新喀里多尼亚"
    },
    "New Zealand":{
        "en":"New Zealand",
        "de":"Neuseeland",
        "ru":"Новая Зеландия",
        "pt":"Nova Zelândia",
        "nl":"Nieuw-Zeeland",
        "fr":"Nouvelle-Zélande",
        "it":"Nuova Zelanda",
        "es":"Nueva Zelanda",
        "pl":"Nowa Zelandia",
        "zh-cn":"新西兰"
    },
    "Nicaragua":{
        "en":"Nicaragua",
        "de":"Nicaragua",
        "ru":"Никарагуа",
        "pt":"Nicarágua",
        "nl":"Nicaragua",
        "fr":"Nicaragua",
        "it":"Nicaragua",
        "es":"Nicaragua",
        "pl":"Nikaragua",
        "zh-cn":"尼加拉瓜"
    },
    "Niger":{
        "en":"Niger",
        "de":"Niger",
        "ru":"Нигер",
        "pt":"Níger",
        "nl":"Niger",
        "fr":"Niger",
        "it":"Niger",
        "es":"Níger",
        "pl":"Niger",
        "zh-cn":"尼日尔"
    },
    "Nigeria":{
        "en":"Nigeria",
        "de":"Nigeria",
        "ru":"Нигерия",
        "pt":"Nigéria",
        "nl":"Nigeria",
        "fr":"Nigéria",
        "it":"Nigeria",
        "es":"Nigeria",
        "pl":"Nigeria",
        "zh-cn":"尼日利亚"
    },
    "Niue":{
        "en":"Niue",
        "de":"Niue",
        "ru":"Ниуэ",
        "pt":"Niue",
        "nl":"Niue",
        "fr":"Niué",
        "it":"Niue",
        "es":"Niue",
        "pl":"Niue",
        "zh-cn":"纽埃"
    },
    "Norfolk Island":{
        "en":"Norfolk Island",
        "de":"Norfolkinsel",
        "ru":"Остров Норфолк",
        "pt":"Ilha Norfolk",
        "nl":"Norfolk",
        "fr":"Île Norfolk",
        "it":"Isola Norfolk",
        "es":"Isla Norfolk",
        "pl":"Norfolk",
        "zh-cn":"诺福克岛"
    },
    "The Republic of North Macedonia":{
        "en":"The Republic of North Macedonia",
        "de":"Nordmazedonien",
        "ru":"Северная Македония",
        "pt":"Macedónia do Norte",
        "nl":"Noord-Macedonië",
        "fr":"Macédoine du Nord",
        "it":"Macedonia del Nord",
        "es":"Macedonia del Norte",
        "pl":"Macedonia Północna",
        "zh-cn":"北马其顿"
    },
    "Northern Mariana Islands":{
        "en":"Northern Mariana Islands",
        "de":"Nördliche Marianen",
        "ru":"Северные Марианские Острова",
        "pt":"Ilhas Marianas do Norte",
        "nl":"Noordelijke Marianen",
        "fr":"Îles Mariannes du Nord",
        "it":"Isole Marianne Settentrionali",
        "es":"Islas Marianas del Norte",
        "pl":"Mariany Północne",
        "zh-cn":"北马里亚纳群岛"
    },
    "Norway":{
        "en":"Norway",
        "de":"Norwegen",
        "ru":"Норвегия",
        "pt":"Noruega",
        "nl":"Noorwegen",
        "fr":"Norvège",
        "it":"Norvegia",
        "es":"Noruega",
        "pl":"Norwegia",
        "zh-cn":"挪威"
    },
    "Oman":{
        "en":"Oman",
        "de":"Oman",
        "ru":"Оман",
        "pt":"Omã",
        "nl":"Oman",
        "fr":"Oman",
        "it":"Oman",
        "es":"Omán",
        "pl":"Oman",
        "zh-cn":"阿曼"
    },
    "Pakistan":{
        "en":"Pakistan",
        "de":"Pakistan",
        "ru":"Пакистан",
        "pt":"Paquistão",
        "nl":"Pakistan",
        "fr":"Pakistan",
        "it":"Pakistan",
        "es":"Pakistán",
        "pl":"Pakistan",
        "zh-cn":"巴基斯坦"
    },
    "Palau":{
        "en":"Palau",
        "de":"Palau",
        "ru":"Палау",
        "pt":"Palau",
        "nl":"Palau",
        "fr":"Palaos",
        "it":"Palau",
        "es":"Palau",
        "pl":"Palau",
        "zh-cn":"帕劳"
    },
    "State of Palestine":{
        "en":"State of Palestine",
        "de":"Staat Palästina",
        "ru":"Государство Палестина",
        "pt":"Territórios palestinos",
        "nl":"Palestina",
        "fr":"Palestine",
        "it":"Stato di Palestina",
        "es":"Palestina",
        "pl":"Palestyna",
        "zh-cn":"巴勒斯坦"
    },
    "Panama":{
        "en":"Panama",
        "de":"Panama",
        "ru":"Панама",
        "pt":"Panamá",
        "nl":"Panama",
        "fr":"Panama",
        "it":"Panamá",
        "es":"Panamá",
        "pl":"Panama",
        "zh-cn":"巴拿马"
    },
    "Papua New Guinea":{
        "en":"Papua New Guinea",
        "de":"Papua-Neuguinea",
        "ru":"Папуа — Новая Гвинея",
        "pt":"Papua-Nova Guiné",
        "nl":"Papoea-Nieuw-Guinea",
        "fr":"Papouasie-Nouvelle-Guinée",
        "it":"Papua Nuova Guinea",
        "es":"Papua Nueva Guinea",
        "pl":"Papua-Nowa Gwinea",
        "zh-cn":"巴布亚新几内亚"
    },
    "Paraguay":{
        "en":"Paraguay",
        "de":"Paraguay",
        "ru":"Парагвай",
        "pt":"Paraguai",
        "nl":"Paraguay",
        "fr":"Paraguay",
        "it":"Paraguay",
        "es":"Paraguay",
        "pl":"Paragwaj",
        "zh-cn":"巴拉圭"
    },
    "Peru":{
        "en":"Peru",
        "de":"Peru",
        "ru":"Перу",
        "pt":"Peru",
        "nl":"Peru",
        "fr":"Pérou",
        "it":"Perù",
        "es":"Perú",
        "pl":"Peru",
        "zh-cn":"秘鲁"
    },
    "Philippines":{
        "en":"Philippines",
        "de":"Philippinen",
        "ru":"Филиппины",
        "pt":"Filipinas",
        "nl":"Filipijnen",
        "fr":"Philippines",
        "it":"Filippine",
        "es":"Filipinas",
        "pl":"Filipiny",
        "zh-cn":"菲律宾"
    },
    "Pitcairn":{
        "en":"Pitcairn",
        "de":"Pitcairninseln",
        "ru":"Острова Питкэрн",
        "pt":"Ilhas Pitcairn",
        "nl":"Pitcairn",
        "fr":"Îles Pitcairn",
        "it":"Isole Pitcairn",
        "es":"Pitcairn",
        "pl":"Pitcairn",
        "zh-cn":"皮特凯恩群岛"
    },
    "Poland":{
        "en":"Poland",
        "de":"Polen",
        "ru":"Польша",
        "pt":"Polónia",
        "nl":"Polen",
        "fr":"Pologne",
        "it":"Polonia",
        "es":"Polonia",
        "pl":"Polska",
        "zh-cn":"波兰"
    },
    "Portugal":{
        "en":"Portugal",
        "de":"Portugal",
        "ru":"Португалия",
        "pt":"Portugal",
        "nl":"Portugal",
        "fr":"Portugal",
        "it":"Portogallo",
        "es":"Portugal",
        "pl":"Portugalia",
        "zh-cn":"葡萄牙"
    },
    "Puerto Rico":{
        "en":"Puerto Rico",
        "de":"Puerto Rico",
        "ru":"Пуэрто-Рико",
        "pt":"Porto Rico",
        "nl":"Puerto Rico",
        "fr":"Porto Rico",
        "it":"Porto Rico",
        "es":"Puerto Rico",
        "pl":"Portoryko",
        "zh-cn":"波多黎各"
    },
    "Qatar":{
        "en":"Qatar",
        "de":"Katar",
        "ru":"Катар",
        "pt":"Qatar",
        "nl":"Qatar",
        "fr":"Qatar",
        "it":"Qatar",
        "es":"Catar",
        "pl":"Katar",
        "zh-cn":"卡塔尔"
    },
    "Reunion":{
        "en":"Reunion",
        "de":"Réunion",
        "ru":"Реюньон",
        "pt":"Reunião",
        "nl":"Réunion",
        "fr":"Réunion",
        "it":"Réunion",
        "es":"Reunión",
        "pl":"Reunion",
        "zh-cn":"留尼汪"
    },
    "Romania":{
        "en":"Romania",
        "de":"Rumänien",
        "ru":"Румыния",
        "pt":"Roménia",
        "nl":"Roemenië",
        "fr":"Roumanie",
        "it":"Romania",
        "es":"Rumanía",
        "pl":"Rumunia",
        "zh-cn":"罗马尼亚"
    },
    "Russian Federation":{
        "en":"Russian Federation",
        "de":"Russische Föderation",
        "ru":"Российская Федерация",
        "pt":"Rússia",
        "nl":"Rusland",
        "fr":"Russie",
        "it":"Russia",
        "es":"Rusia",
        "pl":"Rosja",
        "zh-cn":"俄罗斯"
    },
    "Rwanda":{
        "en":"Rwanda",
        "de":"Ruanda",
        "ru":"Руанда",
        "pt":"Ruanda",
        "nl":"Rwanda",
        "fr":"Rwanda",
        "it":"Ruanda",
        "es":"Ruanda",
        "pl":"Rwanda",
        "zh-cn":"卢旺达"
    },
    "Saint Helena":{
        "en":"Saint Helena",
        "de":"St. Helena",
        "ru":"Острова Святой Елены, Вознесения и Тристан-да-Кунья",
        "pt":"Santa Helena",
        "nl":"Sint-Helena",
        "fr":"Sainte-Hélène",
        "it":"Sant'Elena, Isola di Ascensione e Tristan da Cunha",
        "es":"Santa Helena, Ascensión y Tristán de Acuña",
        "pl":"Wyspa Świętej Heleny, Wyspa Wniebowstąpienia i Tristan da Cunha",
        "zh-cn":"圣赫勒拿、阿森松和 特里斯坦-达库尼亚"
    },
    "Saint Kitts and Nevis":{
        "en":"Saint Kitts and Nevis",
        "de":"St. Kitts und Nevis",
        "ru":"Сент-Китс и Невис",
        "pt":"São Cristóvão e Neves",
        "nl":"Saint Kitts en Nevis",
        "fr":"Saint-Christophe-et-Niévès",
        "it":"Saint Kitts e Nevis",
        "es":"Saint Kitts y Nevis",
        "pl":"Saint Kitts i Nevis",
        "zh-cn":"圣基茨和尼维斯"
    },
    "Saint Lucia":{
        "en":"Saint Lucia",
        "de":"St. Lucia",
        "ru":"Сент-Люсия",
        "pt":"Santa Lúcia",
        "nl":"Saint Lucia",
        "fr":"Sainte-Lucie",
        "it":"Santa Lucia",
        "es":"Santa Lucía",
        "pl":"Saint Lucia",
        "zh-cn":"圣卢西亚"
    },
    "Saint Pierre and Miquelon":{
        "en":"Saint Pierre and Miquelon",
        "de":"Saint-Pierre und Miquelon",
        "ru":"Сен-Пьер и Микелон",
        "pt":"Saint Pierre e Miquelon",
        "nl":"Saint-Pierre en Miquelon",
        "fr":"Saint-Pierre-et-Miquelon",
        "it":"Saint Pierre e Miquelon",
        "es":"San Pedro y Miquelón",
        "pl":"Saint-Pierre i Miquelon",
        "zh-cn":"圣皮埃尔和密克隆"
    },
    "Saint Vincent and the Grenadines":{
        "en":"Saint Vincent and the Grenadines",
        "de":"St. Vincent und die Grenadinen",
        "ru":"Сент-Винсент и Гренадины",
        "pt":"São Vicente e Granadinas",
        "nl":"Saint Vincent en de Grenadines",
        "fr":"Saint-Vincent-et-les-Grenadines",
        "it":"Saint Vincent e Grenadine",
        "es":"San Vicente y las Granadinas",
        "pl":"Saint Vincent i Grenadyny",
        "zh-cn":"圣文森特和格林纳丁斯"
    },
    "Samoa":{
        "en":"Samoa",
        "de":"Samoa",
        "ru":"Самоа",
        "pt":"Samoa",
        "nl":"Samoa",
        "fr":"Samoa",
        "it":"Samoa",
        "es":"Samoa",
        "pl":"Samoa",
        "zh-cn":"萨摩亚"
    },
    "San Marino":{
        "en":"San Marino",
        "de":"San Marino",
        "ru":"Сан-Марино",
        "pt":"San Marino",
        "nl":"San Marino",
        "fr":"Saint-Marin",
        "it":"San Marino",
        "es":"San Marino",
        "pl":"San Marino",
        "zh-cn":"圣马力诺"
    },
    "Sao Tome and Principe":{
        "en":"Sao Tome and Principe",
        "de":"São Tomé und Príncipe",
        "ru":"Сан-Томе и Принсипи",
        "pt":"São Tomé e Príncipe",
        "nl":"São Tomé en Principe",
        "fr":"São Tomé-et-Principe",
        "it":"São Tomé e Príncipe",
        "es":"Santo Tomé y Príncipe",
        "pl":"Wyspy Świętego Tomasza i Książęca",
        "zh-cn":"圣多美和普林西 比"
    },
    "Saudi Arabia":{
        "en":"Saudi Arabia",
        "de":"Saudi-Arabien",
        "ru":"Саудовская Аравия",
        "pt":"Arábia Saudita",
        "nl":"Saudi-Arabië",
        "fr":"Arabie Saoudite",
        "it":"Arabia Saudita",
        "es":"Arabia Saudita",
        "pl":"Arabia Saudyjska",
        "zh-cn":"沙特阿拉 伯"
    },
    "Senegal":{
        "en":"Senegal",
        "de":"Senegal",
        "ru":"Сенегал",
        "pt":"Senegal",
        "nl":"Senegal",
        "fr":"Sénégal",
        "it":"Senegal",
        "es":"Senegal",
        "pl":"Senegal",
        "zh-cn":"塞内加尔"
    },
    "Seychelles":{
        "en":"Seychelles",
        "de":"Seychellen",
        "ru":"Сейшельские Острова",
        "pt":"Seychelles",
        "nl":"Seychellen",
        "fr":"Seychelles",
        "it":"Seychelles",
        "es":"Seychelles",
        "pl":"Seszele",
        "zh-cn":"塞舌尔"
    },
    "Sierra Leone":{
        "en":"Sierra Leone",
        "de":"Sierra Leone",
        "ru":"Сьерра-Леоне",
        "pt":"Serra Leoa",
        "nl":"Sierra Leone",
        "fr":"Sierra Leone",
        "it":"Sierra Leone",
        "es":"Sierra Leona",
        "pl":"Sierra Leone",
        "zh-cn":"塞拉利昂"
    },
    "Singapore":{
        "en":"Singapore",
        "de":"Singapur",
        "ru":"Сингапур",
        "pt":"Singapura",
        "nl":"Singapore",
        "fr":"Singapour",
        "it":"Singapore",
        "es":"Singapur",
        "pl":"Singapur",
        "zh-cn":"新加坡"
    },
    "Slovakia":{
        "en":"Slovakia",
        "de":"Slowakei",
        "ru":"Словакия",
        "pt":"Eslováquia",
        "nl":"Slowakije",
        "fr":"Slovaquie",
        "it":"Slovacchia",
        "es":"Eslovaquia",
        "pl":"Słowacja",
        "zh-cn":"斯洛伐克"
    },
    "Slovenia":{
        "en":"Slovenia",
        "de":"Slowenien",
        "ru":"Словения",
        "pt":"Eslovénia",
        "nl":"Slovenië",
        "fr":"Slovénie",
        "it":"Slovenia",
        "es":"Eslovenia",
        "pl":"Słowenia",
        "zh-cn":"斯洛文尼亚"
    },
    "Solomon Islands":{
        "en":"Solomon Islands",
        "de":"Salomonen",
        "ru":"Соломоновы Острова",
        "pt":"Ilhas Salomão",
        "nl":"Salomonseilanden",
        "fr":"Îles Salomon",
        "it":"Isole Salomone",
        "es":"Islas Salomón",
        "pl":"Wyspy Salomona",
        "zh-cn":"所罗门群岛"
    },
    "Somalia":{
        "en":"Somalia",
        "de":"Somalia",
        "ru":"Сомали",
        "pt":"Somália",
        "nl":"Somalië",
        "fr":"Somalie",
        "it":"Somalia",
        "es":"Somalia",
        "pl":"Somalia",
        "zh-cn":"索马里"
    },
    "South Africa":{
        "en":"South Africa",
        "de":"Südafrika",
        "ru":"ЮАР",
        "pt":"África do Sul",
        "nl":"Zuid-Afrika",
        "fr":"Afrique du Sud",
        "it":"Sudafrica",
        "es":"Sudáfrica",
        "pl":"Południowa Afryka",
        "zh-cn":"南非"
    },
    "South Georgia and the South Sandwich Islands":{
        "en":"South Georgia and the South Sandwich Islands",
        "de":"Südgeorgien und die Südlichen Sandwichinseln",
        "ru":"Южная Георгия и Южные Сандвичевы Острова",
        "pt":"Geórgia do Sul e Ilhas Sandwich do Sul",
        "nl":"Zuid-Georgia en de Zuidelijke Sandwicheilanden",
        "fr":"Géorgie du Sud-et-les Îles Sandwich du Sud",
        "it":"Georgia del Sud e isole Sandwich meridionali",
        "es":"Georgia del Sur y las Islas Sandwich del Sur",
        "pl":"Georgia Południowa i Sandwich Południowy",
        "zh-cn":"南乔治亚和南桑威奇群岛"
    },
    "Spain":{
        "en":"Spain",
        "de":"Spanien",
        "ru":"Испания",
        "pt":"Espanha",
        "nl":"Spanje",
        "fr":"Espagne",
        "it":"Spagna",
        "es":"España",
        "pl":"Hiszpania",
        "zh-cn":"西班牙"
    },
    "Sri Lanka":{
        "en":"Sri Lanka",
        "de":"Sri Lanka",
        "ru":"Шри-Ланка",
        "pt":"Sri Lanka",
        "nl":"Sri Lanka",
        "fr":"Sri Lanka",
        "it":"Sri Lanka",
        "es":"Sri Lanka",
        "pl":"Sri Lanka",
        "zh-cn":"斯里兰卡"
    },
    "Sudan":{
        "en":"Sudan",
        "de":"Sudan",
        "ru":"Судан",
        "pt":"Sudão",
        "nl":"Soedan",
        "fr":"Soudan",
        "it":"Sudan",
        "es":"Sudán",
        "pl":"Sudan",
        "zh-cn":"苏丹"
    },
    "Suriname":{
        "en":"Suriname",
        "de":"Suriname",
        "ru":"Суринам",
        "pt":"Suriname",
        "nl":"Suriname",
        "fr":"Suriname",
        "it":"Suriname",
        "es":"Suriname",
        "pl":"Surinam",
        "zh-cn":"苏里南"
    },
    "Svalbard and Jan Mayen":{
        "en":"Svalbard and Jan Mayen",
        "de":"Svalbard und Jan Mayen",
        "ru":"Шпицберген и Ян-Майен",
        "pt":"Svalbard e Jan Mayen",
        "nl":"Spitsbergen en Jan Mayen",
        "fr":"Svalbard et Île Jan Mayen",
        "it":"Svalbard e Jan Mayen",
        "es":"Svalbard y Jan Mayen",
        "pl":"Svalbard i Jan Mayen",
        "zh-cn":"斯瓦尔巴和扬马延"
    },
    "Eswatini":{
        "en":"Eswatini",
        "de":"Eswatini",
        "ru":"Эсватини",
        "pt":"Essuatíni",
        "nl":"Ngwane, Koninkrijk Eswatini",
        "fr":"Royaume d'Eswatini",
        "it":"Eswatini",
        "es":"Esuatini",
        "pl":"Eswatini",
        "zh-cn":"斯威 士兰"
    },
    "Sweden":{
        "en":"Sweden",
        "de":"Schweden",
        "ru":"Швеция",
        "pt":"Suécia",
        "nl":"Zweden",
        "fr":"Suède",
        "it":"Svezia",
        "es":"Suecia",
        "pl":"Szwecja",
        "zh-cn":"瑞典"
    },
    "Switzerland":{
        "en":"Switzerland",
        "de":"Schweiz",
        "ru":"Швейцария",
        "pt":"Suíça",
        "nl":"Zwitserland",
        "fr":"Suisse",
        "it":"Svizzera",
        "es":"Suiza",
        "pl":"Szwajcaria",
        "zh-cn":"瑞士"
    },
    "Syrian Arab Republic":{
        "en":"Syrian Arab Republic",
        "de":"Syrien, Arabische Republik",
        "ru":"Сирия",
        "pt":"Síria",
        "nl":"Syrië",
        "fr":"Syrie",
        "it":"Siria",
        "es":"República Árabe Siria",
        "pl":"Syria",
        "zh-cn":"叙利亚"
    },
    "Taiwan, Province of China":{
        "en":"Taiwan, Province of China",
        "de":"Taiwan",
        "ru":"Тайвань",
        "pt":"Taiwan",
        "nl":"Taiwan",
        "fr":"Taïwan",
        "it":"Repubblica di Cina",
        "es":"Taiwán",
        "pl":"Tajwan",
        "zh-cn":"中国台湾省"
    },
    "Tajikistan":{
        "en":"Tajikistan",
        "de":"Tadschikistan",
        "ru":"Таджикистан",
        "pt":"Tajiquistão",
        "nl":"Tadzjikistan",
        "fr":"Tadjikistan",
        "it":"Tagikistan",
        "es":"Tayikistán",
        "pl":"Tadżykistan",
        "zh-cn":"塔吉克斯坦"
    },
    "United Republic of Tanzania":{
        "en":"United Republic of Tanzania",
        "de":"Tansania, Vereinigte Republik",
        "ru":"Танзания",
        "pt":"Tanzânia",
        "nl":"Tanzania",
        "fr":"République unie de Tanzanie",
        "it":"Tanzania",
        "es":"Tanzania",
        "pl":"Tanzania",
        "zh-cn":"坦桑尼亚"
    },
    "Thailand":{
        "en":"Thailand",
        "de":"Thailand",
        "ru":"Таиланд",
        "pt":"Tailândia",
        "nl":"Thailand",
        "fr":"Thaïlande",
        "it":"Thailandia",
        "es":"Tailandia",
        "pl":"Tajlandia",
        "zh-cn":"泰国"
    },
    "Timor-Leste":{
        "en":"Timor-Leste",
        "de":"Osttimor",
        "ru":"Восточный Тимор",
        "pt":"Timor-Leste",
        "nl":"Timor Leste",
        "fr":"Timor-Leste",
        "it":"Timor Est",
        "es":"Timor-Leste",
        "pl":"Timor Wschodni",
        "zh-cn":"东帝汶"
    },
    "Togo":{
        "en":"Togo",
        "de":"Togo",
        "ru":"Того",
        "pt":"Togo",
        "nl":"Togo",
        "fr":"Togo",
        "it":"Togo",
        "es":"Togo",
        "pl":"Togo",
        "zh-cn":"多哥"
    },
    "Tokelau":{
        "en":"Tokelau",
        "de":"Tokelau",
        "ru":"Токелау",
        "pt":"Tokelau",
        "nl":"Tokelau",
        "fr":"Tokelau",
        "it":"Tokelau",
        "es":"Tokelau",
        "pl":"Tokelau",
        "zh-cn":"托克劳"
    },
    "Tonga":{
        "en":"Tonga",
        "de":"Tonga",
        "ru":"Тонга",
        "pt":"Tonga",
        "nl":"Tonga",
        "fr":"Tonga",
        "it":"Tonga",
        "es":"Tonga",
        "pl":"Tonga",
        "zh-cn":"汤加"
    },
    "Trinidad and Tobago":{
        "en":"Trinidad and Tobago",
        "de":"Trinidad und Tobago",
        "ru":"Тринидад и Тобаго",
        "pt":"Trindade e Tobago",
        "nl":"Trinidad en Tobago",
        "fr":"Trinité-et-Tobago",
        "it":"Trinidad e Tobago",
        "es":"Trinidad y Tobago",
        "pl":"Trynidad i Tobago",
        "zh-cn":"特立尼达和多巴哥"
    },
    "Tunisia":{
        "en":"Tunisia",
        "de":"Tunesien",
        "ru":"Тунис",
        "pt":"Tunísia",
        "nl":"Tunesië",
        "fr":"Tunisie",
        "it":"Tunisia",
        "es":"Túnez",
        "pl":"Tunezja",
        "zh-cn":"突尼斯"
    },
    "Türkiye":{
        "en":"Türkiye",
        "de":"Türkei",
        "ru":"Турция",
        "pt":"Turquia",
        "nl":"Turkije",
        "fr":"Turquie",
        "it":"Turchia",
        "es":"Turquía",
        "pl":"Turcja",
        "zh-cn":"土耳其"
    },
    "Turkmenistan":{
        "en":"Turkmenistan",
        "de":"Turkmenistan",
        "ru":"Туркмения",
        "pt":"Turquemenistão",
        "nl":"Turkmenistan",
        "fr":"Turkménistan",
        "it":"Turkmenistan",
        "es":"Turkmenistán",
        "pl":"Turkmenistan",
        "zh-cn":"土库 曼斯坦"
    },
    "Turks and Caicos Islands":{
        "en":"Turks and Caicos Islands",
        "de":"Turks- und Caicosinseln",
        "ru":"Теркс и Кайкос",
        "pt":"Ilhas Turcas e Caicos",
        "nl":"Turks- en Caicoseilanden",
        "fr":"Îles Turques-et-Caïques",
        "it":"Isole Turks e Caicos",
        "es":"Islas Turcas y Caicos",
        "pl":"Turks i Caicos",
        "zh-cn":"特克斯和凯科斯群岛"
    },
    "Tuvalu":{
        "en":"Tuvalu",
        "de":"Tuvalu",
        "ru":"Тувалу",
        "pt":"Tuvalu",
        "nl":"Tuvalu",
        "fr":"Tuvalu",
        "it":"Tuvalu",
        "es":"Tuvalu",
        "pl":"Tuvalu",
        "zh-cn":"图瓦卢"
    },
    "Uganda":{
        "en":"Uganda",
        "de":"Uganda",
        "ru":"Уганда",
        "pt":"Uganda",
        "nl":"Oeganda",
        "fr":"Ouganda",
        "it":"Uganda",
        "es":"Uganda",
        "pl":"Uganda",
        "zh-cn":"乌干达"
    },
    "Ukraine":{
        "en":"Ukraine",
        "de":"Ukraine",
        "ru":"Украина",
        "pt":"Ucrânia",
        "nl":"Oekraïne",
        "fr":"Ukraine",
        "it":"Ucraina",
        "es":"Ucrania",
        "pl":"Ukraina",
        "zh-cn":"乌克兰"
    },
    "United Arab Emirates":{
        "en":"United Arab Emirates",
        "de":"Vereinigte Arabische Emirate",
        "ru":"ОАЭ",
        "pt":"Emirados Árabes Unidos",
        "nl":"Verenigde Arabische Emiraten",
        "fr":"Émirats Arabes Unis",
        "it":"Emirati Arabi Uniti",
        "es":"Emiratos Árabes Unidos",
        "pl":"Zjednoczone Emiraty Arabskie",
        "zh-cn":"阿联酋"
    },
    "United Kingdom":{
        "en":"United Kingdom",
        "de":"Vereinigtes Königreich",
        "ru":"Великобритания",
        "pt":"Reino Unido",
        "nl":"Groot-Brittannië",
        "fr":"Royaume-Uni",
        "it":"Regno Unito",
        "es":"Reino Unido",
        "pl":"Wielka Brytania",
        "zh-cn":"英国"
    },
    "United States of America":{
        "en":"United States of America",
        "de":"Vereinigte Staaten von Amerika",
        "ru":"США",
        "pt":"Estados Unidos",
        "nl":"Verenigde Staten van Amerika",
        "fr":"États-Unis d'Amérique",
        "it":"Stati Uniti d'America",
        "es":"Estados Unidos",
        "pl":"Stany Zjednoczone",
        "zh-cn":"美国"
    },
    "United States Minor Outlying Islands":{
        "en":"United States Minor Outlying Islands",
        "de":"United States Minor Outlying Islands",
        "ru":"Внешние малые острова (США)",
        "pt":"Ilhas Distantes dos EUA",
        "nl":"Ver afgelegen eilandjes van de Verenigde Staten",
        "fr":"Îles mineures éloignées des États-Unis",
        "it":"Isole minori esterne degli Stati Uniti",
        "es":"Islas Ultramarinas Menores de los Estados Unidos",
        "pl":"Dalekie Wyspy Mniejsze Stanów Zjednoczonych",
        "zh-cn":"美国本土外小岛屿"
    },
    "Uruguay":{
        "en":"Uruguay",
        "de":"Uruguay",
        "ru":"Уругвай",
        "pt":"Uruguai",
        "nl":"Uruguay",
        "fr":"Uruguay",
        "it":"Uruguay",
        "es":"Uruguay",
        "pl":"Urugwaj",
        "zh-cn":"乌拉圭"
    },
    "Uzbekistan":{
        "en":"Uzbekistan",
        "de":"Usbekistan",
        "ru":"Узбекистан",
        "pt":"Uzbequistão",
        "nl":"Oezbekistan",
        "fr":"Ouzbékistan",
        "it":"Uzbekistan",
        "es":"Uzbekistán",
        "pl":"Uzbekistan",
        "zh-cn":"乌兹别克斯坦"
    },
    "Vanuatu":{
        "en":"Vanuatu",
        "de":"Vanuatu",
        "ru":"Вануату",
        "pt":"Vanuatu",
        "nl":"Vanuatu",
        "fr":"Vanuatu",
        "it":"Vanuatu",
        "es":"Vanuatu",
        "pl":"Vanuatu",
        "zh-cn":"瓦努阿图"
    },
    "Venezuela":{
        "en":"Venezuela",
        "de":"Venezuela",
        "ru":"Венесуэла",
        "pt":"Venezuela",
        "nl":"Venezuela",
        "fr":"Venezuela",
        "it":"Venezuela",
        "es":"Venezuela",
        "pl":"Wenezuela",
        "zh-cn":"委内瑞拉"
    },
    "Vietnam":{
        "en":"Vietnam",
        "de":"Vietnam",
        "ru":"Вьетнам",
        "pt":"Vietname",
        "nl":"Vietnam",
        "fr":"Vietnam",
        "it":"Vietnam",
        "es":"Vietnam",
        "pl":"Wietnam",
        "zh-cn":"越 南"
    },
    "Virgin Islands, British":{
        "en":"Virgin Islands, British",
        "de":"Britische Jungferninseln",
        "ru":"Виргинские Острова (Великобритания)",
        "pt":"Ilhas Virgens Britânicas",
        "nl":"Maagdeneilanden, Britse",
        "fr":"Îles vierges britanniques",
        "it":"Isole Vergini Britanniche",
        "es":"Islas Vírgenes británicas",
        "pl":"Brytyjskie Wyspy Dziewicze",
        "zh-cn":"英属维尔京群岛"
    },
    "Virgin Islands, U.S.":{
        "en":"Virgin Islands, U.S.",
        "de":"Amerikanische Jungferninseln",
        "ru":"Виргинские Острова (США)",
        "pt":"Ilhas Virgens Americanas",
        "nl":"Maagdeneilanden, Amerikaanse",
        "fr":"Îles vierges américaines",
        "it":"Isole Vergini Americane",
        "es":"Islas Vírgenes de los Estados Unidos",
        "pl":"Wyspy Dziewicze Stanów Zjednoczonych",
        "zh-cn":"美属维尔京群岛"
    },
    "Wallis and Futuna":{
        "en":"Wallis and Futuna",
        "de":"Wallis und Futuna",
        "ru":"Уоллис и Футуна",
        "pt":"Wallis e Futuna",
        "nl":"Wallis en Futuna",
        "fr":"Wallis-et-Futuna",
        "it":"Wallis e Futuna",
        "es":"Wallis y Futuna",
        "pl":"Wallis i Futuna",
        "zh-cn":"瓦利斯和富图纳"
    },
    "Western Sahara":{
        "en":"Western Sahara",
        "de":"Westsahara",
        "ru":"САДР",
        "pt":"Saara Ocidental",
        "nl":"Westelijke Sahara",
        "fr":"Sahara occidental",
        "it":"Sahara Occidentale",
        "es":"Sahara Occidental",
        "pl":"Sahara Zachodnia",
        "zh-cn":"阿拉伯撒哈拉民主共和国"
    },
    "Yemen":{
        "en":"Yemen",
        "de":"Jemen",
        "ru":"Йемен",
        "pt":"Iémen",
        "nl":"Jemen",
        "fr":"Yémen",
        "it":"Yemen",
        "es":"Yemen",
        "pl":"Jemen",
        "zh-cn":"也门"
    },
    "Zambia":{
        "en":"Zambia",
        "de":"Sambia",
        "ru":"Замбия",
        "pt":"Zâmbia",
        "nl":"Zambia",
        "fr":"Zambie",
        "it":"Zambia",
        "es":"Zambia",
        "pl":"Zambia",
        "zh-cn":"赞比亚"
    },
    "Zimbabwe":{
        "en":"Zimbabwe",
        "de":"Simbabwe",
        "ru":"Зимбабве",
        "pt":"Zimbábue",
        "nl":"Zimbabwe",
        "fr":"Zimbabwe",
        "it":"Zimbabwe",
        "es":"Zimbabue",
        "pl":"Zimbabwe",
        "zh-cn":"津巴布韦"
    },
    "Åland Islands":{
        "en":"Åland Islands",
        "de":"Åland",
        "ru":"Аландские острова",
        "pt":"Ilhas Åland",
        "nl":"Åland",
        "fr":"Åland",
        "it":"Isole Åland",
        "es":"Islas Åland",
        "pl":"Wyspy Alandzkie",
        "zh-cn":"奥兰"
    },
    "Bonaire, Sint Eustatius and Saba":{
        "en":"Bonaire, Sint Eustatius and Saba",
        "de":"Bonaire",
        "ru":"Бонэйр, Синт-Эстатиус и Саба",
        "pt":"Países Baixos Caribenhos",
        "nl":"Bonaire, Sint Eustatius en Saba",
        "fr":"Bonaire, Saint-Eustache et Saba",
        "it":"Isole BES",
        "es":"Bonaire, San Eustaquio y Saba",
        "pl":"Bonaire, Sint Eustatius i Saba",
        "zh-cn":"荷兰加勒比区"
    },
    "Curaçao":{
        "en":"Curaçao",
        "de":"Curaçao",
        "ru":"Кюрасао",
        "pt":"Curaçao",
        "nl":"Curaçao",
        "fr":"Curaçao",
        "it":"Curaçao",
        "es":"Curaçao",
        "pl":"Curaçao",
        "zh-cn":"库拉索"
    },
    "Guernsey":{
        "en":"Guernsey",
        "de":"Guernsey",
        "ru":"Гернси",
        "pt":"Guernsey",
        "nl":"Guernsey",
        "fr":"Guernesey",
        "it":"Guernsey",
        "es":"Guernsey",
        "pl":"Guernsey",
        "zh-cn":"根西"
    },
    "Isle of Man":{
        "en":"Isle of Man",
        "de":"Insel Man",
        "ru":"Остров Мэн",
        "pt":"Ilha de Man",
        "nl":"Man Eiland",
        "fr":"Île de Man",
        "it":"Isola di Man",
        "es":"Isla de Man",
        "pl":"Wyspa Man",
        "zh-cn":"马恩岛"
    },
    "Jersey":{
        "en":"Jersey",
        "de":"Jersey",
        "ru":"Джерси",
        "pt":"Jersey",
        "nl":"Jersey",
        "fr":"Jersey",
        "it":"Jersey",
        "es":"Jersey",
        "pl":"Jersey",
        "zh-cn":"泽西"
    },
    "Montenegro":{
        "en":"Montenegro",
        "de":"Montenegro",
        "ru":"Черногория",
        "pt":"Montenegro",
        "nl":"Montenegro",
        "fr":"Monténégro",
        "it":"Montenegro",
        "es":"Montenegro",
        "pl":"Czarnogóra",
        "zh-cn":"黑山"
    },
    "Saint Barthélemy":{
        "en":"Saint Barthélemy",
        "de":"Saint-Barthélemy",
        "ru":"Сен-Бартелеми",
        "pt":"São Bartolomeu",
        "nl":"Saint Barthélemy",
        "fr":"Saint-Barthélemy",
        "it":"Saint-Barthélemy",
        "es":"Saint Barthélemy",
        "pl":"Saint-Barthélemy",
        "zh-cn":"圣巴泰勒米"
    },
    "Saint Martin (French part)":{
        "en":"Saint Martin (French part)",
        "de":"Saint-Martin",
        "ru":"Сен-Мартен",
        "pt":"São Martinho",
        "nl":"Sint-Maarten (Frans deel)",
        "fr":"Saint-Martin (partie française)",
        "it":"Saint-Martin",
        "es":"Saint Martin (francesa)",
        "pl":"Saint-Martin",
        "zh-cn":"法属圣马丁"
    },
    "Serbia":{
        "en":"Serbia",
        "de":"Serbien",
        "ru":"Сербия",
        "pt":"Sérvia",
        "nl":"Servië",
        "fr":"Serbie",
        "it":"Serbia",
        "es":"Serbia",
        "pl":"Serbia",
        "zh-cn":"塞尔维亚"
    },
    "Sint Maarten (Dutch part)":{
        "en":"Sint Maarten (Dutch part)",
        "de":"Sint Maarten",
        "ru":"Синт-Мартен",
        "pt":"São Martinho",
        "nl":"Sint Maarten",
        "fr":"Saint-Martin (partie néerlandaise)",
        "it":"Sint Maarten",
        "es":"Sint Maarten (neerlandesa)",
        "pl":"Sint Maarten",
        "zh-cn":"荷属圣马丁"
    },
    "South Sudan":{
        "en":"South Sudan",
        "de":"Südsudan",
        "ru":"Южный Судан",
        "pt":"Sudão do Sul",
        "nl":"Zuid-Soedan",
        "fr":"Soudan du Sud",
        "it":"Sudan del Sud",
        "es":"Sudán del Sur",
        "pl":"Sudan Południowy",
        "zh-cn":"南苏丹"
    },
    "Kosovo":{
        "en":"Kosovo",
        "de":"Kosovo",
        "ru":"Косово",
        "pt":"Kosovo",
        "nl":"Kosovo",
        "fr":"Kosovo",
        "it":"Kosovo",
        "es":"Kosovo",
        "pl":"Kosowo",
        "zh-cn":"科索沃"
    }
};