/*global systemDictionary:true */
"use strict";

systemDictionary = {
    "eufy-security adapter settings": {
        "en": "Adapter settings for eufy-security",
        "de": "Adaptereinstellungen für eufy-security",
        "ru": "Настройки адаптера для eufy-security",
        "pt": "Configurações do adaptador para eufy-security",
        "nl": "Adapterinstellingen voor eufy-security",
        "fr": "Paramètres d'adaptateur pour eufy-security",
        "it": "Impostazioni dell'adattatore per eufy-security",
        "es": "Ajustes del adaptador para eufy-security",
        "pl": "Ustawienia adaptera dla eufy-security",
        "zh-cn": "eufy-security的适配器设置"
    },
    "Username": {
        "en": "Username",
        "de": "Benutzername",
        "ru": "Имя пользователя",
        "pt": "Nome de usuário",
        "nl": "Gebruikersnaam",
        "fr": "Nom d'utilisateur",
        "it": "Nome utente",
        "es": "Nombre de usuario",
        "pl": "Nazwa użytkownika",
        "zh-cn": "帳號"
    },
    "Password": {
        "en": "Password",
        "de": "Passwort",
        "ru": "Пароль",
        "pt": "Senha",
        "nl": "Wachtwoord",
        "fr": "Mot de passe",
        "it": "Password",
        "es": "Contraseña",
        "pl": "Hasło",
        "zh-cn": "密码"
    },
    "Polling interval (min)": {
        "en": "Polling interval (min)",
        "de": "Abfrageintervall (min)",
        "ru": "Интервал опроса (мин)",
        "pt": "Intervalo de sondagem (min)",
        "nl": "Polling-interval (min)",
        "fr": "Intervalle d'interrogation (min)",
        "it": "Intervallo di polling (min)",
        "es": "Intervalo de sondeo (min)",
        "pl": "Okres odpytywania (min)",
        "zh-cn": "轮询间隔（分钟）"
    },
    "Max camera livestream duration (sec)": {
        "en": "Max camera livestream duration (sec)",
        "de": "Maximale Livestream-Dauer der Kamera (Sek.)",
        "ru": "Максимальная продолжительность прямой трансляции с камеры (сек)",
        "pt": "Duração máxima da transmissão ao vivo da câmera (segundos)",
        "nl": "Max. Duur livestream camera (sec)",
        "fr": "Durée maximale de la diffusion en direct de la caméra (s)",
        "it": "Durata massima del live streaming della videocamera (sec)",
        "es": "Duración máxima de la transmisión en vivo de la cámara (segundos)",
        "pl": "Maksymalny czas trwania transmisji na żywo z kamery (s)",
        "zh-cn": "相机直播的最大持续时间（秒）"
    },
    "Time in seconds before event reset": {
        "en": "Time in seconds before event reset",
        "de": "Zeit in Sekunden vor dem Zurücksetzen des Ereignisses",
        "ru": "Время в секундах до сброса события",
        "pt": "Tempo em segundos antes da redefinição do evento",
        "nl": "Tijd in seconden voordat de gebeurtenis wordt gereset",
        "fr": "Temps en secondes avant la réinitialisation de l'événement",
        "it": "Tempo in secondi prima del ripristino dell'evento",
        "es": "Tiempo en segundos antes del reinicio del evento",
        "pl": "Czas w sekundach do zresetowania zdarzenia",
        "zh-cn": "事件重置之前的时间（以秒为单位）"
    },
    "Authentication settings": {
        "en": "Authentication settings",
        "de": "Authentifizierungseinstellungen",
        "ru": "Настройки аутентификации",
        "pt": "Configurações de autenticação",
        "nl": "Authenticatie-instellingen",
        "fr": "Paramètres d'authentification",
        "it": "Impostazioni di autenticazione",
        "es": "Configuración de autenticación",
        "pl": "Ustawienia uwierzytelniania",
        "zh-cn": "验证设定"
    },
    "Other settings": {
        "en": "Other settings",
        "de": "Andere Einstellungen",
        "ru": "Другие настройки",
        "pt": "Outros ajustes",
        "nl": "Andere instellingen",
        "fr": "Autres réglages",
        "it": "Altre impostazioni",
        "es": "Otros ajustes",
        "pl": "Inne ustawienia",
        "zh-cn": "其他设定"
    },
    "Settings": {
        "en": "Settings",
        "de": "Einstellungen",
        "ru": "Настройки",
        "pt": "Configurações",
        "nl": "Instellingen",
        "fr": "Réglages",
        "it": "Impostazioni",
        "es": "Ajustes",
        "pl": "Ustawienia",
        "zh-cn": "设定值"
    },
    "Main settings": {
        "en": "Main settings",
        "de": "Haupteinstellungen",
        "ru": "Основные параметры",
        "pt": "Configurações principais",
        "nl": "Belangrijkste instellingen",
        "fr": "Réglages principaux",
        "it": "Impostazioni principali",
        "es": "Ajustes principales",
        "pl": "Ustawienia główne",
        "zh-cn": "主要设定"
    },
    "Livestream settings": {
        "en": "Livestream settings",
        "de": "Livestream-Einstellungen",
        "ru": "Настройки прямой трансляции",
        "pt": "Configurações de transmissão ao vivo",
        "nl": "Livestream-instellingen",
        "fr": "Paramètres de diffusion en direct",
        "it": "Impostazioni live streaming",
        "es": "Configuración de transmisión en vivo",
        "pl": "Ustawienia transmisji na żywo",
        "zh-cn": "直播设置"
    },
    "Only local connection": {
        "en": "Only local connection",
        "de": "Nur lokale Verbindung",
        "ru": "Только локальное подключение",
        "pt": "Apenas conexão local",
        "nl": "Alleen lokale verbinding",
        "fr": "Uniquement connexion locale",
        "it": "Solo connessione locale",
        "es": "Solo conexión local",
        "pl": "Tylko połączenie lokalne",
        "zh-cn": "仅本地连接"
    },
    "Quickest connection": {
        "en": "Quickest connection",
        "de": "Schnellste Verbindung",
        "ru": "Самое быстрое соединение",
        "pt": "Conexão mais rápida",
        "nl": "Snelste verbinding",
        "fr": "Connexion la plus rapide",
        "it": "Connessione più veloce",
        "es": "Conexión más rápida",
        "pl": "Najszybsze połączenie",
        "zh-cn": "最快的连接"
    },
    "P2P connection type": {
        "en": "P2P connection type",
        "de": "P2P-Verbindungstyp",
        "ru": "Тип подключения P2P",
        "pt": "Tipo de conexão P2P",
        "nl": "P2P-verbindingstype",
        "fr": "Type de connexion P2P",
        "it": "Tipo di connessione P2P",
        "es": "Tipo de conexión P2P",
        "pl": "Typ połączenia P2P",
        "zh-cn": "P2P连接类型"
    },
    "Accept incoming invitations": {
        "en": "Accept incoming invitations",
        "de": "Eingehende Einladungen annehmen",
        "ru": "Принимать входящие приглашения",
        "pt": "Aceitar os convites recebidos",
        "nl": "Accepteer inkomende uitnodigingen",
        "fr": "Accepter les invitations entrantes",
        "it": "Accetta inviti in arrivo",
        "es": "Aceptar invitaciones entrantes",
        "pl": "Przyjmowanie zaproszeń przychodzących",
        "zh-cn": "接受收到的邀请"
    },
    "Alarm sound duration (sec)": {
        "en": "Alarm sound duration (sec)",
        "de": "Dauer des Alarmtons (Sek.)",
        "ru": "Длительность звукового сигнала тревоги (сек)",
        "pt": "Duração do som do alarme (seg)",
        "nl": "Duur alarmgeluid (sec)",
        "fr": "Durée du son de l'alarme (sec)",
        "it": "Durata del suono dell'allarme (sec)",
        "es": "Duración del sonido de la alarma (s)",
        "pl": "Czas trwania dźwięku alarmu (sek.)",
        "zh-cn": "警报声持续时间（秒"
    },
    "Automatically download video": {
        "en": "Automatically download video",
        "de": "Automatisches Herunterladen von Videos",
        "ru": "Автоматическая загрузка видео",
        "pt": "Descarregar vídeo automaticamente",
        "nl": "Video automatisch downloaden",
        "fr": "Téléchargement automatique de la vidéo",
        "it": "Scarica automaticamente il video",
        "es": "Descarga automática de vídeo",
        "pl": "Automatycznie pobieraj wideo",
        "zh-cn": "自动下载视频"
    }
};